apiVersion: apps/v1
kind: Deployment
metadata:
  name: yawm-deployment
  namespace: yawm-project
  labels:
    app: yawm-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yawm-backend-app
  template:
    metadata:
      labels:
        app: yawm-backend-app
    spec:
      initContainers:
          - name: init-postgres-service
            image: postgres:14
            command: [
                      'sh',
                      '-c',
                      'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432; do echo waiting for database; sleep 5; done;'
                    ]

      containers:
        - image: devalv/yawm-backend:latest
          imagePullPolicy: Always
          name: sample-container
          envFrom:
          - secretRef:
              name: yawm-secret
          ports:
            - containerPort: 5000
              name: fastapi
          readinessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 5000
              path: /api/health
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
