apiVersion: apps/v1
kind: Deployment
metadata:
  name: yawm-deployment
  namespace: yawm-project
  labels:
    app: yawm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yawm-backend-app
  template:
    metadata:
      labels:
        app: yawm-backend-app
    spec:
      containers:
        - image: devalv/yawm-backend:latest
          imagePullPolicy: Always
          name: sample-container
          envFrom:
          - secretRef:
              name: yawm-secret
          ports:
            - containerPort: 8000
              name: fastapi
          readinessProbe:
            httpGet:
              port: 8000
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 8000
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
