apiVersion: v1
kind: Service
metadata:
  name: yawm-service
  namespace: yawm-project
  labels:
    app: yawm-backend
spec:
  type: NodePort
  selector:
    app: yawm-backend-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30800
