repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--config=backend/pyproject.toml]
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: pflake8
        exclude: 'tests/'
        additional_dependencies:
          - pyproject-flake8
          - flake8-builtins
          - flake8-bugbear
          - flake8-quotes
          - flake8-eradicate
          - flake8-mock
          - flake8-pie
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - flake8-variables-names
        args: [--config=backend/pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [--config-file=backend/pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args:
          [
            --config=frontend/.prettierrc,
            --ignore-path=frontend/.prettierignore,
          ]
