version: "3.7"
services:

  db:
    container_name: yawm-db
    image: postgres:13
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    restart: unless-stopped

  app:
    container_name: yawm-backend-api
    build:
      context: .
      dockerfile: ./backend/docker/python/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend/:/opt/yawm/app/
    environment:
      - PYTHONPATH=/opt/yawm/app
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_PROTOCOL=${API_PROTOCOL}
      - API_DOMAIN=${API_DOMAIN}
      - CRAWLER_USER_AGENT=${CRAWLER_USER_AGENT}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRETS_JSON=${GOOGLE_CLIENT_SECRETS_JSON}
      - GOOGLE_USERINFO_SCOPE=${GOOGLE_USERINFO_SCOPE}
      - OAUTHLIB_INSECURE_TRANSPORT=1
    working_dir: /opt/yawm/app
    command: sh -c "pipenv install && sleep 3 && pipenv run alembic upgrade head && pipenv run python main.py"
    depends_on:
      - db

  frontend-app:
    container_name: yawm-frontend
    image: node:lts-alpine
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/opt/yawm/frontend
    environment:
      - API_URL=${API_URL}
      - NODE_PATH=${NODE_PATH}
    working_dir: /opt/yawm/frontend
#    command: sh -c "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
    command: sh -c "npm start"
    depends_on:
      - app
