version: "3.7"
services:

  db:
    container_name: yawm-db
    image: postgres:14
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    restart: unless-stopped

  app:
    container_name: yawm-backend-api
    build:
      context: .
      dockerfile: ./backend/docker/python/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend/:/home/app
    environment:
      - DB_HOST=db
      - API_HOST=0.0.0.0
      - API_PORT=${API_PORT}
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db

  # frontend-app:
  #   image: devalv/yawm:frontend-0.1.0
  #   container_name: yawm-frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - app
  #     - db
  #   environment:
  #     - REACT_APP_API_ORIGIN=${API_PROTOCOL}://${API_HOST}:${API_PORT}
  #     - REACT_APP_API_URL=${REACT_APP_API_ORIGIN}/api
  #     - REACT_APP_API_V1_URL=${REACT_APP_API_URL}/v1
  #     - REACT_APP_API_V2_URL=${REACT_APP_API_URL}/v2
  #     - REACT_APP_HEALTH_URL=${REACT_APP_API_URL}/health
  #     - REACT_APP_STATE=nonrandom-docker-local-state
  #   working_dir: /opt/yawm/frontend
  #   command: sh -c "npm start"
  #   stdin_open: true

  # caddy:
  #   image: "caddy:2.4.6-alpine"
  #   restart: unless-stopped
  #   environment:
  #     - DOMAIN_NAME=${DOMAIN_NAME}
  #     - API_PORT=${API_PORT}
  #     - TLS_EMAIL=${TLS_EMAIL}
  #   volumes:
  #     - ./caddy/certs:/root/.caddy
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 2019:2019
  #   depends_on:
  #     - app
  #     - frontend-app
