version: "3.7"
services:

  db:
    container_name: yawm-db
    image: postgres:13
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    restart: always
    network_mode: "host"

  app:
    container_name: yawm-backend-api
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/opt/yawm/app/
    environment:
      - PYTHONPATH=/opt/yawm/app
    working_dir: /opt/yawm/app
    command: sh -c "sleep 5 && pipenv run alembic upgrade head && pipenv run uvicorn api:app --reload"
    depends_on:
      - db
    network_mode: "host"
