version: "3.7"
services:

  db-tests:
    container_name: yawm-tests-db
    image: postgres:13
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    network_mode: "host"

  app-tests:
    container_name: yawm-tests-backend-api
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./backend/:/opt/yawm/app/
    environment:
      - PYTHONPATH=/opt/yawm/app
    working_dir: /opt/yawm/app
    command: sh -c "sleep 5 && pipenv run pytest"
    depends_on:
      - db-tests
    network_mode: "host"
