version: "3.7"

services:

  db-tests:
    container_name: yawm-tests-db
    image: postgres:14
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}

  app-tests:
    container_name: yawm-tests-backend-api
    build:
      context: .
      dockerfile: ./backend/docker/tests-python/Dockerfile
    environment:
      - DB_HOST=db-tests
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_PROTOCOL=${API_PROTOCOL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db-tests
