version: "3.7"
services:

  db:
    container_name: yawm-db
    image: postgres:14
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    restart: unless-stopped

  app:
    container_name: yawm-backend-api
    build:
      context: .
      dockerfile: ./backend/docker/python/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend/:/home/app
    environment:
      - DB_HOST=db
      - API_HOST=0.0.0.0
      - API_PORT=${API_PORT}
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db

  frontend-app:
    build:
      context: .
      dockerfile: ./frontend/docker/react/Dockerfile
    volumes:
      - ./frontend:/home/app
    container_name: yawm-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
      - db
    environment:
      - REACT_APP_API_ORIGIN=http://${API_DOMAIN}:${API_PORT}
      - REACT_APP_API_URL=http://${API_DOMAIN}:${API_PORT}/api
      - REACT_APP_API_V1_URL=http://${API_DOMAIN}:${API_PORT}/api/v1
      - REACT_APP_API_V2_URL=http://${API_DOMAIN}:${API_PORT}/api/v2
      - REACT_APP_HEALTH_URL=http://${API_DOMAIN}:${API_PORT}/api/health
      - REACT_APP_STATE=nonrandom-docker-local-state
      - REACT_APP_SENTRY_DSN=https://efba663b9e534fd0876d7a40ba3c191d@o1201644.ingest.sentry.io/6373679
    stdin_open: true
    command: "npm start --host 0.0.0.0"
