# docker system prune -a -f --volumes && docker-compose --env-file ./backend/.env up
version: "3.7"
services:

  db:
    container_name: yawm-backend
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
