# docker system prune -a -f --volumes && docker-compose --env-file ./backend/tests/.env -f docker-compose-test.yml  up
version: "3.7"
services:

  db-tests:
    container_name: yawm-tests-db
    image: postgres:13
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    network_mode: "host"
