version: "3.8"

x-env: &yawm_tests_env
  env_file:
    - "../backend/tests/.env"
  environment:
    - POSTGRES_DB=${DB_DATABASE}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - PYTHONPATH=/opt/yawm/app
    - DB_HOST=db-tests
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_DATABASE=${DB_DATABASE}

services:

  db-tests:
    container_name: yawm-tests-db
    image: postgres:13
    <<: *yawm_tests_env
    command: -p ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app-tests:
    container_name: yawm-tests-backend-api
    build:
      context: ..
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ../backend/:/opt/yawm/app/
    <<: *yawm_tests_env
    working_dir: /opt/yawm/app
    command: sh -c "sleep 5 && pipenv run python -m pytest"
    depends_on:
      - db-tests
