# -*- coding: utf-8 -*-
"""Product updates.

Revision ID: 47ff2b4be24c
Revises: b13c977f28a7
Create Date: 2021-05-05 21:58:30.121282

"""
from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47ff2b4be24c"
down_revision = "b13c977f28a7"
branch_labels = None
depends_on = None


def upgrade():
    """Apply changes on database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "price")
    op.add_column(
        "product_wishlist", sa.Column("substitutable", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    """Revert changes on database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_wishlist", "substitutable")
    op.add_column(
        "product",
        sa.Column(
            "price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
