# -*- coding: utf-8 -*-
"""Initial migration.

Revision ID: 85b9bef9bbee
Revises:
Create Date: 2021-05-10 13:23:59.761097

"""
from alembic import op

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "85b9bef9bbee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Apply changes on database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.Unicode(length=255), nullable=False),
        sa.Column("url", sa.Unicode(length=8000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "wishlist",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.Unicode(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wishlist_products",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("wishlist_id", postgresql.UUID(), nullable=False),
        sa.Column("product_id", postgresql.UUID(), nullable=False),
        sa.Column("substitutable", sa.Boolean(), nullable=False),
        sa.Column("reserved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wishlist_id"], ["wishlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """Revert changes on database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wishlist_products")
    op.drop_table("wishlist")
    op.drop_table("product")
    # ### end Alembic commands ###
