# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["TestEmptyWishlist.test_empty_wishlist_full_update 1"] = {
    "name": "test-updated",
    "username": "user_mock",
}

snapshots["TestEmptyWishlist.test_empty_wishlist_full_update_admin 1"] = {
    "name": "test-updated",
    "username": "user_mock",
}

snapshots["TestEmptyWishlist.test_empty_wishlist_read 1"] = {
    "name": "test",
    "username": "user_mock",
}

snapshots["TestEmptyWishlist.test_empty_wishlists 1"] = [
    {"name": "test4", "username": "user_mock"},
    {"name": "test3", "username": "user_mock"},
    {"name": "test2", "username": "user_mock"},
    {"name": "test1", "username": "user_mock"},
]

snapshots["TestEmptyWishlist.test_empty_wishlists_paginator_limit 1"] = [
    {"name": "test4", "username": "user_mock"},
    {"name": "test3", "username": "user_mock"},
]

snapshots["TestEmptyWishlist.test_wishlist_create 1"] = {
    "name": "Wishlist1",
    "username": "user_mock",
}

snapshots["TestProduct.test_product_create 1"] = {
    "name": "Product1",
    "url": "https://devyatkin.dev",
    "username": "user_mock",
}

snapshots["TestProduct.test_product_full_update 1"] = {
    "name": "test-updated",
    "url": "https://ya.ru",
    "username": "user_mock",
}

snapshots["TestProduct.test_product_full_update_admin 1"] = {
    "name": "test-updated",
    "url": "https://ya.ru",
    "username": "user_mock",
}

snapshots["TestProduct.test_product_paginator_limit 1"] = {
    "items": [
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "user_mock"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "user_mock"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "user_mock"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "user_mock"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "user_mock"},
    ],
    "links": {
        "first": "/v1/product?size=5&page=1",
        "last": "/v1/product?size=5&page=2",
        "next": "/v1/product?size=5&page=2",
        "prev": None,
        "self": "/v1/product?size=5",
    },
    "page": 1,
    "size": 5,
    "total": 9,
}

snapshots["TestProduct.test_product_partial_update 1"] = {
    "name": "partial-updated-name",
    "url": "https://devyatkin.dev/1",
    "username": "user_mock",
}

snapshots["TestProduct.test_product_partial_update_admin 1"] = {
    "name": "partial-updated-name",
    "url": "https://devyatkin.dev/1",
    "username": "user_mock",
}

snapshots["TestProduct.test_product_read 1"] = {
    "name": "test",
    "url": "https://devyatkin.dev/1",
    "username": "user_mock",
}

snapshots["TestProduct.test_products 1"] = {
    "items": [
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "user_mock"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "user_mock"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "user_mock"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "user_mock"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "user_mock"},
        {"name": "test4", "url": "https://devyatkin.dev/4", "username": "user_mock"},
        {"name": "test3", "url": "https://devyatkin.dev/3", "username": "user_mock"},
        {"name": "test2", "url": "https://devyatkin.dev/2", "username": "user_mock"},
        {"name": "test1", "url": "https://devyatkin.dev/1", "username": "user_mock"},
    ],
    "links": {
        "first": "/v1/product?page=1",
        "last": "/v1/product?page=1",
        "next": None,
        "prev": None,
        "self": "/v1/product",
    },
    "page": 1,
    "size": 50,
    "total": 9,
}

snapshots["TestProductPaginator.test_default_paginator 1"] = {
    "items": [
        {
            "name": "test149",
            "url": "https://devyatkin.dev/149",
            "username": "user_mock",
        },
        {
            "name": "test148",
            "url": "https://devyatkin.dev/148",
            "username": "user_mock",
        },
        {
            "name": "test147",
            "url": "https://devyatkin.dev/147",
            "username": "user_mock",
        },
        {
            "name": "test146",
            "url": "https://devyatkin.dev/146",
            "username": "user_mock",
        },
        {
            "name": "test145",
            "url": "https://devyatkin.dev/145",
            "username": "user_mock",
        },
        {
            "name": "test144",
            "url": "https://devyatkin.dev/144",
            "username": "user_mock",
        },
        {
            "name": "test143",
            "url": "https://devyatkin.dev/143",
            "username": "user_mock",
        },
        {
            "name": "test142",
            "url": "https://devyatkin.dev/142",
            "username": "user_mock",
        },
        {
            "name": "test141",
            "url": "https://devyatkin.dev/141",
            "username": "user_mock",
        },
        {
            "name": "test140",
            "url": "https://devyatkin.dev/140",
            "username": "user_mock",
        },
        {
            "name": "test139",
            "url": "https://devyatkin.dev/139",
            "username": "user_mock",
        },
        {
            "name": "test138",
            "url": "https://devyatkin.dev/138",
            "username": "user_mock",
        },
        {
            "name": "test137",
            "url": "https://devyatkin.dev/137",
            "username": "user_mock",
        },
        {
            "name": "test136",
            "url": "https://devyatkin.dev/136",
            "username": "user_mock",
        },
        {
            "name": "test135",
            "url": "https://devyatkin.dev/135",
            "username": "user_mock",
        },
        {
            "name": "test134",
            "url": "https://devyatkin.dev/134",
            "username": "user_mock",
        },
        {
            "name": "test133",
            "url": "https://devyatkin.dev/133",
            "username": "user_mock",
        },
        {
            "name": "test132",
            "url": "https://devyatkin.dev/132",
            "username": "user_mock",
        },
        {
            "name": "test131",
            "url": "https://devyatkin.dev/131",
            "username": "user_mock",
        },
        {
            "name": "test130",
            "url": "https://devyatkin.dev/130",
            "username": "user_mock",
        },
        {
            "name": "test129",
            "url": "https://devyatkin.dev/129",
            "username": "user_mock",
        },
        {
            "name": "test128",
            "url": "https://devyatkin.dev/128",
            "username": "user_mock",
        },
        {
            "name": "test127",
            "url": "https://devyatkin.dev/127",
            "username": "user_mock",
        },
        {
            "name": "test126",
            "url": "https://devyatkin.dev/126",
            "username": "user_mock",
        },
        {
            "name": "test125",
            "url": "https://devyatkin.dev/125",
            "username": "user_mock",
        },
        {
            "name": "test124",
            "url": "https://devyatkin.dev/124",
            "username": "user_mock",
        },
        {
            "name": "test123",
            "url": "https://devyatkin.dev/123",
            "username": "user_mock",
        },
        {
            "name": "test122",
            "url": "https://devyatkin.dev/122",
            "username": "user_mock",
        },
        {
            "name": "test121",
            "url": "https://devyatkin.dev/121",
            "username": "user_mock",
        },
        {
            "name": "test120",
            "url": "https://devyatkin.dev/120",
            "username": "user_mock",
        },
        {
            "name": "test119",
            "url": "https://devyatkin.dev/119",
            "username": "user_mock",
        },
        {
            "name": "test118",
            "url": "https://devyatkin.dev/118",
            "username": "user_mock",
        },
        {
            "name": "test117",
            "url": "https://devyatkin.dev/117",
            "username": "user_mock",
        },
        {
            "name": "test116",
            "url": "https://devyatkin.dev/116",
            "username": "user_mock",
        },
        {
            "name": "test115",
            "url": "https://devyatkin.dev/115",
            "username": "user_mock",
        },
        {
            "name": "test114",
            "url": "https://devyatkin.dev/114",
            "username": "user_mock",
        },
        {
            "name": "test113",
            "url": "https://devyatkin.dev/113",
            "username": "user_mock",
        },
        {
            "name": "test112",
            "url": "https://devyatkin.dev/112",
            "username": "user_mock",
        },
        {
            "name": "test111",
            "url": "https://devyatkin.dev/111",
            "username": "user_mock",
        },
        {
            "name": "test110",
            "url": "https://devyatkin.dev/110",
            "username": "user_mock",
        },
        {
            "name": "test109",
            "url": "https://devyatkin.dev/109",
            "username": "user_mock",
        },
        {
            "name": "test108",
            "url": "https://devyatkin.dev/108",
            "username": "user_mock",
        },
        {
            "name": "test107",
            "url": "https://devyatkin.dev/107",
            "username": "user_mock",
        },
        {
            "name": "test106",
            "url": "https://devyatkin.dev/106",
            "username": "user_mock",
        },
        {
            "name": "test105",
            "url": "https://devyatkin.dev/105",
            "username": "user_mock",
        },
        {
            "name": "test104",
            "url": "https://devyatkin.dev/104",
            "username": "user_mock",
        },
        {
            "name": "test103",
            "url": "https://devyatkin.dev/103",
            "username": "user_mock",
        },
        {
            "name": "test102",
            "url": "https://devyatkin.dev/102",
            "username": "user_mock",
        },
        {
            "name": "test101",
            "url": "https://devyatkin.dev/101",
            "username": "user_mock",
        },
        {
            "name": "test100",
            "url": "https://devyatkin.dev/100",
            "username": "user_mock",
        },
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestProductPaginator.test_first_page_paginator 1"] = {
    "items": [
        {
            "name": "test149",
            "url": "https://devyatkin.dev/149",
            "username": "user_mock",
        },
        {
            "name": "test148",
            "url": "https://devyatkin.dev/148",
            "username": "user_mock",
        },
        {
            "name": "test147",
            "url": "https://devyatkin.dev/147",
            "username": "user_mock",
        },
        {
            "name": "test146",
            "url": "https://devyatkin.dev/146",
            "username": "user_mock",
        },
        {
            "name": "test145",
            "url": "https://devyatkin.dev/145",
            "username": "user_mock",
        },
        {
            "name": "test144",
            "url": "https://devyatkin.dev/144",
            "username": "user_mock",
        },
        {
            "name": "test143",
            "url": "https://devyatkin.dev/143",
            "username": "user_mock",
        },
        {
            "name": "test142",
            "url": "https://devyatkin.dev/142",
            "username": "user_mock",
        },
        {
            "name": "test141",
            "url": "https://devyatkin.dev/141",
            "username": "user_mock",
        },
        {
            "name": "test140",
            "url": "https://devyatkin.dev/140",
            "username": "user_mock",
        },
        {
            "name": "test139",
            "url": "https://devyatkin.dev/139",
            "username": "user_mock",
        },
        {
            "name": "test138",
            "url": "https://devyatkin.dev/138",
            "username": "user_mock",
        },
        {
            "name": "test137",
            "url": "https://devyatkin.dev/137",
            "username": "user_mock",
        },
        {
            "name": "test136",
            "url": "https://devyatkin.dev/136",
            "username": "user_mock",
        },
        {
            "name": "test135",
            "url": "https://devyatkin.dev/135",
            "username": "user_mock",
        },
        {
            "name": "test134",
            "url": "https://devyatkin.dev/134",
            "username": "user_mock",
        },
        {
            "name": "test133",
            "url": "https://devyatkin.dev/133",
            "username": "user_mock",
        },
        {
            "name": "test132",
            "url": "https://devyatkin.dev/132",
            "username": "user_mock",
        },
        {
            "name": "test131",
            "url": "https://devyatkin.dev/131",
            "username": "user_mock",
        },
        {
            "name": "test130",
            "url": "https://devyatkin.dev/130",
            "username": "user_mock",
        },
        {
            "name": "test129",
            "url": "https://devyatkin.dev/129",
            "username": "user_mock",
        },
        {
            "name": "test128",
            "url": "https://devyatkin.dev/128",
            "username": "user_mock",
        },
        {
            "name": "test127",
            "url": "https://devyatkin.dev/127",
            "username": "user_mock",
        },
        {
            "name": "test126",
            "url": "https://devyatkin.dev/126",
            "username": "user_mock",
        },
        {
            "name": "test125",
            "url": "https://devyatkin.dev/125",
            "username": "user_mock",
        },
        {
            "name": "test124",
            "url": "https://devyatkin.dev/124",
            "username": "user_mock",
        },
        {
            "name": "test123",
            "url": "https://devyatkin.dev/123",
            "username": "user_mock",
        },
        {
            "name": "test122",
            "url": "https://devyatkin.dev/122",
            "username": "user_mock",
        },
        {
            "name": "test121",
            "url": "https://devyatkin.dev/121",
            "username": "user_mock",
        },
        {
            "name": "test120",
            "url": "https://devyatkin.dev/120",
            "username": "user_mock",
        },
        {
            "name": "test119",
            "url": "https://devyatkin.dev/119",
            "username": "user_mock",
        },
        {
            "name": "test118",
            "url": "https://devyatkin.dev/118",
            "username": "user_mock",
        },
        {
            "name": "test117",
            "url": "https://devyatkin.dev/117",
            "username": "user_mock",
        },
        {
            "name": "test116",
            "url": "https://devyatkin.dev/116",
            "username": "user_mock",
        },
        {
            "name": "test115",
            "url": "https://devyatkin.dev/115",
            "username": "user_mock",
        },
        {
            "name": "test114",
            "url": "https://devyatkin.dev/114",
            "username": "user_mock",
        },
        {
            "name": "test113",
            "url": "https://devyatkin.dev/113",
            "username": "user_mock",
        },
        {
            "name": "test112",
            "url": "https://devyatkin.dev/112",
            "username": "user_mock",
        },
        {
            "name": "test111",
            "url": "https://devyatkin.dev/111",
            "username": "user_mock",
        },
        {
            "name": "test110",
            "url": "https://devyatkin.dev/110",
            "username": "user_mock",
        },
        {
            "name": "test109",
            "url": "https://devyatkin.dev/109",
            "username": "user_mock",
        },
        {
            "name": "test108",
            "url": "https://devyatkin.dev/108",
            "username": "user_mock",
        },
        {
            "name": "test107",
            "url": "https://devyatkin.dev/107",
            "username": "user_mock",
        },
        {
            "name": "test106",
            "url": "https://devyatkin.dev/106",
            "username": "user_mock",
        },
        {
            "name": "test105",
            "url": "https://devyatkin.dev/105",
            "username": "user_mock",
        },
        {
            "name": "test104",
            "url": "https://devyatkin.dev/104",
            "username": "user_mock",
        },
        {
            "name": "test103",
            "url": "https://devyatkin.dev/103",
            "username": "user_mock",
        },
        {
            "name": "test102",
            "url": "https://devyatkin.dev/102",
            "username": "user_mock",
        },
        {
            "name": "test101",
            "url": "https://devyatkin.dev/101",
            "username": "user_mock",
        },
        {
            "name": "test100",
            "url": "https://devyatkin.dev/100",
            "username": "user_mock",
        },
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"name": "test49", "url": "https://devyatkin.dev/49", "username": "user_mock"},
        {"name": "test48", "url": "https://devyatkin.dev/48", "username": "user_mock"},
        {"name": "test47", "url": "https://devyatkin.dev/47", "username": "user_mock"},
        {"name": "test46", "url": "https://devyatkin.dev/46", "username": "user_mock"},
        {"name": "test45", "url": "https://devyatkin.dev/45", "username": "user_mock"},
        {"name": "test44", "url": "https://devyatkin.dev/44", "username": "user_mock"},
        {"name": "test43", "url": "https://devyatkin.dev/43", "username": "user_mock"},
        {"name": "test42", "url": "https://devyatkin.dev/42", "username": "user_mock"},
        {"name": "test41", "url": "https://devyatkin.dev/41", "username": "user_mock"},
        {"name": "test40", "url": "https://devyatkin.dev/40", "username": "user_mock"},
        {"name": "test39", "url": "https://devyatkin.dev/39", "username": "user_mock"},
        {"name": "test38", "url": "https://devyatkin.dev/38", "username": "user_mock"},
        {"name": "test37", "url": "https://devyatkin.dev/37", "username": "user_mock"},
        {"name": "test36", "url": "https://devyatkin.dev/36", "username": "user_mock"},
        {"name": "test35", "url": "https://devyatkin.dev/35", "username": "user_mock"},
        {"name": "test34", "url": "https://devyatkin.dev/34", "username": "user_mock"},
        {"name": "test33", "url": "https://devyatkin.dev/33", "username": "user_mock"},
        {"name": "test32", "url": "https://devyatkin.dev/32", "username": "user_mock"},
        {"name": "test31", "url": "https://devyatkin.dev/31", "username": "user_mock"},
        {"name": "test30", "url": "https://devyatkin.dev/30", "username": "user_mock"},
        {"name": "test29", "url": "https://devyatkin.dev/29", "username": "user_mock"},
        {"name": "test28", "url": "https://devyatkin.dev/28", "username": "user_mock"},
        {"name": "test27", "url": "https://devyatkin.dev/27", "username": "user_mock"},
        {"name": "test26", "url": "https://devyatkin.dev/26", "username": "user_mock"},
        {"name": "test25", "url": "https://devyatkin.dev/25", "username": "user_mock"},
        {"name": "test24", "url": "https://devyatkin.dev/24", "username": "user_mock"},
        {"name": "test23", "url": "https://devyatkin.dev/23", "username": "user_mock"},
        {"name": "test22", "url": "https://devyatkin.dev/22", "username": "user_mock"},
        {"name": "test21", "url": "https://devyatkin.dev/21", "username": "user_mock"},
        {"name": "test20", "url": "https://devyatkin.dev/20", "username": "user_mock"},
        {"name": "test19", "url": "https://devyatkin.dev/19", "username": "user_mock"},
        {"name": "test18", "url": "https://devyatkin.dev/18", "username": "user_mock"},
        {"name": "test17", "url": "https://devyatkin.dev/17", "username": "user_mock"},
        {"name": "test16", "url": "https://devyatkin.dev/16", "username": "user_mock"},
        {"name": "test15", "url": "https://devyatkin.dev/15", "username": "user_mock"},
        {"name": "test14", "url": "https://devyatkin.dev/14", "username": "user_mock"},
        {"name": "test13", "url": "https://devyatkin.dev/13", "username": "user_mock"},
        {"name": "test12", "url": "https://devyatkin.dev/12", "username": "user_mock"},
        {"name": "test11", "url": "https://devyatkin.dev/11", "username": "user_mock"},
        {"name": "test10", "url": "https://devyatkin.dev/10", "username": "user_mock"},
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "user_mock"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "user_mock"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "user_mock"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "user_mock"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "user_mock"},
        {"name": "test4", "url": "https://devyatkin.dev/4", "username": "user_mock"},
        {"name": "test3", "url": "https://devyatkin.dev/3", "username": "user_mock"},
        {"name": "test2", "url": "https://devyatkin.dev/2", "username": "user_mock"},
        {"name": "test1", "url": "https://devyatkin.dev/1", "username": "user_mock"},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "user_mock"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "user_mock"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "user_mock"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "user_mock"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "user_mock"},
        {"name": "test4", "url": "https://devyatkin.dev/4", "username": "user_mock"},
        {"name": "test3", "url": "https://devyatkin.dev/3", "username": "user_mock"},
        {"name": "test2", "url": "https://devyatkin.dev/2", "username": "user_mock"},
        {"name": "test1", "url": "https://devyatkin.dev/1", "username": "user_mock"},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestProductPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"name": "test99", "url": "https://devyatkin.dev/99", "username": "user_mock"},
        {"name": "test98", "url": "https://devyatkin.dev/98", "username": "user_mock"},
        {"name": "test97", "url": "https://devyatkin.dev/97", "username": "user_mock"},
        {"name": "test96", "url": "https://devyatkin.dev/96", "username": "user_mock"},
        {"name": "test95", "url": "https://devyatkin.dev/95", "username": "user_mock"},
        {"name": "test94", "url": "https://devyatkin.dev/94", "username": "user_mock"},
        {"name": "test93", "url": "https://devyatkin.dev/93", "username": "user_mock"},
        {"name": "test92", "url": "https://devyatkin.dev/92", "username": "user_mock"},
        {"name": "test91", "url": "https://devyatkin.dev/91", "username": "user_mock"},
        {"name": "test90", "url": "https://devyatkin.dev/90", "username": "user_mock"},
        {"name": "test89", "url": "https://devyatkin.dev/89", "username": "user_mock"},
        {"name": "test88", "url": "https://devyatkin.dev/88", "username": "user_mock"},
        {"name": "test87", "url": "https://devyatkin.dev/87", "username": "user_mock"},
        {"name": "test86", "url": "https://devyatkin.dev/86", "username": "user_mock"},
        {"name": "test85", "url": "https://devyatkin.dev/85", "username": "user_mock"},
        {"name": "test84", "url": "https://devyatkin.dev/84", "username": "user_mock"},
        {"name": "test83", "url": "https://devyatkin.dev/83", "username": "user_mock"},
        {"name": "test82", "url": "https://devyatkin.dev/82", "username": "user_mock"},
        {"name": "test81", "url": "https://devyatkin.dev/81", "username": "user_mock"},
        {"name": "test80", "url": "https://devyatkin.dev/80", "username": "user_mock"},
        {"name": "test79", "url": "https://devyatkin.dev/79", "username": "user_mock"},
        {"name": "test78", "url": "https://devyatkin.dev/78", "username": "user_mock"},
        {"name": "test77", "url": "https://devyatkin.dev/77", "username": "user_mock"},
        {"name": "test76", "url": "https://devyatkin.dev/76", "username": "user_mock"},
        {"name": "test75", "url": "https://devyatkin.dev/75", "username": "user_mock"},
        {"name": "test74", "url": "https://devyatkin.dev/74", "username": "user_mock"},
        {"name": "test73", "url": "https://devyatkin.dev/73", "username": "user_mock"},
        {"name": "test72", "url": "https://devyatkin.dev/72", "username": "user_mock"},
        {"name": "test71", "url": "https://devyatkin.dev/71", "username": "user_mock"},
        {"name": "test70", "url": "https://devyatkin.dev/70", "username": "user_mock"},
        {"name": "test69", "url": "https://devyatkin.dev/69", "username": "user_mock"},
        {"name": "test68", "url": "https://devyatkin.dev/68", "username": "user_mock"},
        {"name": "test67", "url": "https://devyatkin.dev/67", "username": "user_mock"},
        {"name": "test66", "url": "https://devyatkin.dev/66", "username": "user_mock"},
        {"name": "test65", "url": "https://devyatkin.dev/65", "username": "user_mock"},
        {"name": "test64", "url": "https://devyatkin.dev/64", "username": "user_mock"},
        {"name": "test63", "url": "https://devyatkin.dev/63", "username": "user_mock"},
        {"name": "test62", "url": "https://devyatkin.dev/62", "username": "user_mock"},
        {"name": "test61", "url": "https://devyatkin.dev/61", "username": "user_mock"},
        {"name": "test60", "url": "https://devyatkin.dev/60", "username": "user_mock"},
        {"name": "test59", "url": "https://devyatkin.dev/59", "username": "user_mock"},
        {"name": "test58", "url": "https://devyatkin.dev/58", "username": "user_mock"},
        {"name": "test57", "url": "https://devyatkin.dev/57", "username": "user_mock"},
        {"name": "test56", "url": "https://devyatkin.dev/56", "username": "user_mock"},
        {"name": "test55", "url": "https://devyatkin.dev/55", "username": "user_mock"},
        {"name": "test54", "url": "https://devyatkin.dev/54", "username": "user_mock"},
        {"name": "test53", "url": "https://devyatkin.dev/53", "username": "user_mock"},
        {"name": "test52", "url": "https://devyatkin.dev/52", "username": "user_mock"},
        {"name": "test51", "url": "https://devyatkin.dev/51", "username": "user_mock"},
        {"name": "test50", "url": "https://devyatkin.dev/50", "username": "user_mock"},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {
            "name": "test149",
            "url": "https://devyatkin.dev/149",
            "username": "user_mock",
        },
        {
            "name": "test148",
            "url": "https://devyatkin.dev/148",
            "username": "user_mock",
        },
        {
            "name": "test147",
            "url": "https://devyatkin.dev/147",
            "username": "user_mock",
        },
        {
            "name": "test146",
            "url": "https://devyatkin.dev/146",
            "username": "user_mock",
        },
        {
            "name": "test145",
            "url": "https://devyatkin.dev/145",
            "username": "user_mock",
        },
        {
            "name": "test144",
            "url": "https://devyatkin.dev/144",
            "username": "user_mock",
        },
        {
            "name": "test143",
            "url": "https://devyatkin.dev/143",
            "username": "user_mock",
        },
        {
            "name": "test142",
            "url": "https://devyatkin.dev/142",
            "username": "user_mock",
        },
        {
            "name": "test141",
            "url": "https://devyatkin.dev/141",
            "username": "user_mock",
        },
        {
            "name": "test140",
            "url": "https://devyatkin.dev/140",
            "username": "user_mock",
        },
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}

snapshots["TestWPPaginator.test_default_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestWPPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestWPPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_default_paginator 1"] = {
    "items": [
        {"name": "test149", "username": "user_mock"},
        {"name": "test148", "username": "user_mock"},
        {"name": "test147", "username": "user_mock"},
        {"name": "test146", "username": "user_mock"},
        {"name": "test145", "username": "user_mock"},
        {"name": "test144", "username": "user_mock"},
        {"name": "test143", "username": "user_mock"},
        {"name": "test142", "username": "user_mock"},
        {"name": "test141", "username": "user_mock"},
        {"name": "test140", "username": "user_mock"},
        {"name": "test139", "username": "user_mock"},
        {"name": "test138", "username": "user_mock"},
        {"name": "test137", "username": "user_mock"},
        {"name": "test136", "username": "user_mock"},
        {"name": "test135", "username": "user_mock"},
        {"name": "test134", "username": "user_mock"},
        {"name": "test133", "username": "user_mock"},
        {"name": "test132", "username": "user_mock"},
        {"name": "test131", "username": "user_mock"},
        {"name": "test130", "username": "user_mock"},
        {"name": "test129", "username": "user_mock"},
        {"name": "test128", "username": "user_mock"},
        {"name": "test127", "username": "user_mock"},
        {"name": "test126", "username": "user_mock"},
        {"name": "test125", "username": "user_mock"},
        {"name": "test124", "username": "user_mock"},
        {"name": "test123", "username": "user_mock"},
        {"name": "test122", "username": "user_mock"},
        {"name": "test121", "username": "user_mock"},
        {"name": "test120", "username": "user_mock"},
        {"name": "test119", "username": "user_mock"},
        {"name": "test118", "username": "user_mock"},
        {"name": "test117", "username": "user_mock"},
        {"name": "test116", "username": "user_mock"},
        {"name": "test115", "username": "user_mock"},
        {"name": "test114", "username": "user_mock"},
        {"name": "test113", "username": "user_mock"},
        {"name": "test112", "username": "user_mock"},
        {"name": "test111", "username": "user_mock"},
        {"name": "test110", "username": "user_mock"},
        {"name": "test109", "username": "user_mock"},
        {"name": "test108", "username": "user_mock"},
        {"name": "test107", "username": "user_mock"},
        {"name": "test106", "username": "user_mock"},
        {"name": "test105", "username": "user_mock"},
        {"name": "test104", "username": "user_mock"},
        {"name": "test103", "username": "user_mock"},
        {"name": "test102", "username": "user_mock"},
        {"name": "test101", "username": "user_mock"},
        {"name": "test100", "username": "user_mock"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"name": "test149", "username": "user_mock"},
        {"name": "test148", "username": "user_mock"},
        {"name": "test147", "username": "user_mock"},
        {"name": "test146", "username": "user_mock"},
        {"name": "test145", "username": "user_mock"},
        {"name": "test144", "username": "user_mock"},
        {"name": "test143", "username": "user_mock"},
        {"name": "test142", "username": "user_mock"},
        {"name": "test141", "username": "user_mock"},
        {"name": "test140", "username": "user_mock"},
        {"name": "test139", "username": "user_mock"},
        {"name": "test138", "username": "user_mock"},
        {"name": "test137", "username": "user_mock"},
        {"name": "test136", "username": "user_mock"},
        {"name": "test135", "username": "user_mock"},
        {"name": "test134", "username": "user_mock"},
        {"name": "test133", "username": "user_mock"},
        {"name": "test132", "username": "user_mock"},
        {"name": "test131", "username": "user_mock"},
        {"name": "test130", "username": "user_mock"},
        {"name": "test129", "username": "user_mock"},
        {"name": "test128", "username": "user_mock"},
        {"name": "test127", "username": "user_mock"},
        {"name": "test126", "username": "user_mock"},
        {"name": "test125", "username": "user_mock"},
        {"name": "test124", "username": "user_mock"},
        {"name": "test123", "username": "user_mock"},
        {"name": "test122", "username": "user_mock"},
        {"name": "test121", "username": "user_mock"},
        {"name": "test120", "username": "user_mock"},
        {"name": "test119", "username": "user_mock"},
        {"name": "test118", "username": "user_mock"},
        {"name": "test117", "username": "user_mock"},
        {"name": "test116", "username": "user_mock"},
        {"name": "test115", "username": "user_mock"},
        {"name": "test114", "username": "user_mock"},
        {"name": "test113", "username": "user_mock"},
        {"name": "test112", "username": "user_mock"},
        {"name": "test111", "username": "user_mock"},
        {"name": "test110", "username": "user_mock"},
        {"name": "test109", "username": "user_mock"},
        {"name": "test108", "username": "user_mock"},
        {"name": "test107", "username": "user_mock"},
        {"name": "test106", "username": "user_mock"},
        {"name": "test105", "username": "user_mock"},
        {"name": "test104", "username": "user_mock"},
        {"name": "test103", "username": "user_mock"},
        {"name": "test102", "username": "user_mock"},
        {"name": "test101", "username": "user_mock"},
        {"name": "test100", "username": "user_mock"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"name": "test49", "username": "user_mock"},
        {"name": "test48", "username": "user_mock"},
        {"name": "test47", "username": "user_mock"},
        {"name": "test46", "username": "user_mock"},
        {"name": "test45", "username": "user_mock"},
        {"name": "test44", "username": "user_mock"},
        {"name": "test43", "username": "user_mock"},
        {"name": "test42", "username": "user_mock"},
        {"name": "test41", "username": "user_mock"},
        {"name": "test40", "username": "user_mock"},
        {"name": "test39", "username": "user_mock"},
        {"name": "test38", "username": "user_mock"},
        {"name": "test37", "username": "user_mock"},
        {"name": "test36", "username": "user_mock"},
        {"name": "test35", "username": "user_mock"},
        {"name": "test34", "username": "user_mock"},
        {"name": "test33", "username": "user_mock"},
        {"name": "test32", "username": "user_mock"},
        {"name": "test31", "username": "user_mock"},
        {"name": "test30", "username": "user_mock"},
        {"name": "test29", "username": "user_mock"},
        {"name": "test28", "username": "user_mock"},
        {"name": "test27", "username": "user_mock"},
        {"name": "test26", "username": "user_mock"},
        {"name": "test25", "username": "user_mock"},
        {"name": "test24", "username": "user_mock"},
        {"name": "test23", "username": "user_mock"},
        {"name": "test22", "username": "user_mock"},
        {"name": "test21", "username": "user_mock"},
        {"name": "test20", "username": "user_mock"},
        {"name": "test19", "username": "user_mock"},
        {"name": "test18", "username": "user_mock"},
        {"name": "test17", "username": "user_mock"},
        {"name": "test16", "username": "user_mock"},
        {"name": "test15", "username": "user_mock"},
        {"name": "test14", "username": "user_mock"},
        {"name": "test13", "username": "user_mock"},
        {"name": "test12", "username": "user_mock"},
        {"name": "test11", "username": "user_mock"},
        {"name": "test10", "username": "user_mock"},
        {"name": "test9", "username": "user_mock"},
        {"name": "test8", "username": "user_mock"},
        {"name": "test7", "username": "user_mock"},
        {"name": "test6", "username": "user_mock"},
        {"name": "test5", "username": "user_mock"},
        {"name": "test4", "username": "user_mock"},
        {"name": "test3", "username": "user_mock"},
        {"name": "test2", "username": "user_mock"},
        {"name": "test1", "username": "user_mock"},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test9", "username": "user_mock"},
        {"name": "test8", "username": "user_mock"},
        {"name": "test7", "username": "user_mock"},
        {"name": "test6", "username": "user_mock"},
        {"name": "test5", "username": "user_mock"},
        {"name": "test4", "username": "user_mock"},
        {"name": "test3", "username": "user_mock"},
        {"name": "test2", "username": "user_mock"},
        {"name": "test1", "username": "user_mock"},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"name": "test99", "username": "user_mock"},
        {"name": "test98", "username": "user_mock"},
        {"name": "test97", "username": "user_mock"},
        {"name": "test96", "username": "user_mock"},
        {"name": "test95", "username": "user_mock"},
        {"name": "test94", "username": "user_mock"},
        {"name": "test93", "username": "user_mock"},
        {"name": "test92", "username": "user_mock"},
        {"name": "test91", "username": "user_mock"},
        {"name": "test90", "username": "user_mock"},
        {"name": "test89", "username": "user_mock"},
        {"name": "test88", "username": "user_mock"},
        {"name": "test87", "username": "user_mock"},
        {"name": "test86", "username": "user_mock"},
        {"name": "test85", "username": "user_mock"},
        {"name": "test84", "username": "user_mock"},
        {"name": "test83", "username": "user_mock"},
        {"name": "test82", "username": "user_mock"},
        {"name": "test81", "username": "user_mock"},
        {"name": "test80", "username": "user_mock"},
        {"name": "test79", "username": "user_mock"},
        {"name": "test78", "username": "user_mock"},
        {"name": "test77", "username": "user_mock"},
        {"name": "test76", "username": "user_mock"},
        {"name": "test75", "username": "user_mock"},
        {"name": "test74", "username": "user_mock"},
        {"name": "test73", "username": "user_mock"},
        {"name": "test72", "username": "user_mock"},
        {"name": "test71", "username": "user_mock"},
        {"name": "test70", "username": "user_mock"},
        {"name": "test69", "username": "user_mock"},
        {"name": "test68", "username": "user_mock"},
        {"name": "test67", "username": "user_mock"},
        {"name": "test66", "username": "user_mock"},
        {"name": "test65", "username": "user_mock"},
        {"name": "test64", "username": "user_mock"},
        {"name": "test63", "username": "user_mock"},
        {"name": "test62", "username": "user_mock"},
        {"name": "test61", "username": "user_mock"},
        {"name": "test60", "username": "user_mock"},
        {"name": "test59", "username": "user_mock"},
        {"name": "test58", "username": "user_mock"},
        {"name": "test57", "username": "user_mock"},
        {"name": "test56", "username": "user_mock"},
        {"name": "test55", "username": "user_mock"},
        {"name": "test54", "username": "user_mock"},
        {"name": "test53", "username": "user_mock"},
        {"name": "test52", "username": "user_mock"},
        {"name": "test51", "username": "user_mock"},
        {"name": "test50", "username": "user_mock"},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test149", "username": "user_mock"},
        {"name": "test148", "username": "user_mock"},
        {"name": "test147", "username": "user_mock"},
        {"name": "test146", "username": "user_mock"},
        {"name": "test145", "username": "user_mock"},
        {"name": "test144", "username": "user_mock"},
        {"name": "test143", "username": "user_mock"},
        {"name": "test142", "username": "user_mock"},
        {"name": "test141", "username": "user_mock"},
        {"name": "test140", "username": "user_mock"},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}
