# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["TestEmptyWishlist.test_empty_wishlist_full_update 1"] = {
    "name": "test-updated"
}

snapshots["TestEmptyWishlist.test_empty_wishlist_full_update_admin 1"] = {
    "name": "test-updated"
}

snapshots["TestEmptyWishlist.test_empty_wishlist_read 1"] = {"name": "test"}

snapshots["TestEmptyWishlist.test_empty_wishlists 1"] = [
    {"name": "test1"},
    {"name": "test2"},
    {"name": "test3"},
    {"name": "test4"},
]

snapshots["TestEmptyWishlist.test_empty_wishlists_paginator_limit 1"] = [
    {"name": "test1"},
    {"name": "test2"},
]

snapshots["TestEmptyWishlist.test_wishlist_create 1"] = {"name": "Wishlist1"}

snapshots["TestProduct.test_product_create 1"] = {
    "name": "Product1",
    "url": "https://devyatkin.dev",
}

snapshots["TestProduct.test_product_full_update 1"] = {
    "name": "test-updated",
    "url": "https://ya.ru",
}

snapshots["TestProduct.test_product_full_update_admin 1"] = {
    "name": "test-updated",
    "url": "https://ya.ru",
}

snapshots["TestProduct.test_product_paginator_limit 1"] = {
    "items": [
        {"name": "test1", "url": "https://devyatkin.dev/1"},
        {"name": "test2", "url": "https://devyatkin.dev/2"},
        {"name": "test3", "url": "https://devyatkin.dev/3"},
        {"name": "test4", "url": "https://devyatkin.dev/4"},
        {"name": "test5", "url": "https://devyatkin.dev/5"},
    ],
    "links": {
        "first": "/v1/product?size=5&page=1",
        "last": "/v1/product?size=5&page=2",
        "next": "/v1/product?size=5&page=2",
        "prev": None,
        "self": "/v1/product?size=5",
    },
    "page": 1,
    "size": 5,
    "total": 9,
}

snapshots["TestProduct.test_product_partial_update 1"] = {
    "name": "partial-updated-name",
    "url": "https://devyatkin.dev/1",
}

snapshots["TestProduct.test_product_partial_update_admin 1"] = {
    "name": "partial-updated-name",
    "url": "https://devyatkin.dev/1",
}

snapshots["TestProduct.test_product_read 1"] = {
    "name": "test",
    "url": "https://devyatkin.dev/1",
}

snapshots["TestProduct.test_products 1"] = {
    "items": [
        {"name": "test1", "url": "https://devyatkin.dev/1"},
        {"name": "test2", "url": "https://devyatkin.dev/2"},
        {"name": "test3", "url": "https://devyatkin.dev/3"},
        {"name": "test4", "url": "https://devyatkin.dev/4"},
        {"name": "test5", "url": "https://devyatkin.dev/5"},
        {"name": "test6", "url": "https://devyatkin.dev/6"},
        {"name": "test7", "url": "https://devyatkin.dev/7"},
        {"name": "test8", "url": "https://devyatkin.dev/8"},
        {"name": "test9", "url": "https://devyatkin.dev/9"},
    ],
    "links": {
        "first": "/v1/product?page=1",
        "last": "/v1/product?page=1",
        "next": None,
        "prev": None,
        "self": "/v1/product",
    },
    "page": 1,
    "size": 50,
    "total": 9,
}

snapshots["TestProductPaginator.test_default_paginator 1"] = {
    "items": [
        {"name": "test1", "url": "https://devyatkin.dev/1"},
        {"name": "test2", "url": "https://devyatkin.dev/2"},
        {"name": "test3", "url": "https://devyatkin.dev/3"},
        {"name": "test4", "url": "https://devyatkin.dev/4"},
        {"name": "test5", "url": "https://devyatkin.dev/5"},
        {"name": "test6", "url": "https://devyatkin.dev/6"},
        {"name": "test7", "url": "https://devyatkin.dev/7"},
        {"name": "test8", "url": "https://devyatkin.dev/8"},
        {"name": "test9", "url": "https://devyatkin.dev/9"},
        {"name": "test10", "url": "https://devyatkin.dev/10"},
        {"name": "test11", "url": "https://devyatkin.dev/11"},
        {"name": "test12", "url": "https://devyatkin.dev/12"},
        {"name": "test13", "url": "https://devyatkin.dev/13"},
        {"name": "test14", "url": "https://devyatkin.dev/14"},
        {"name": "test15", "url": "https://devyatkin.dev/15"},
        {"name": "test16", "url": "https://devyatkin.dev/16"},
        {"name": "test17", "url": "https://devyatkin.dev/17"},
        {"name": "test18", "url": "https://devyatkin.dev/18"},
        {"name": "test19", "url": "https://devyatkin.dev/19"},
        {"name": "test20", "url": "https://devyatkin.dev/20"},
        {"name": "test21", "url": "https://devyatkin.dev/21"},
        {"name": "test22", "url": "https://devyatkin.dev/22"},
        {"name": "test23", "url": "https://devyatkin.dev/23"},
        {"name": "test24", "url": "https://devyatkin.dev/24"},
        {"name": "test25", "url": "https://devyatkin.dev/25"},
        {"name": "test26", "url": "https://devyatkin.dev/26"},
        {"name": "test27", "url": "https://devyatkin.dev/27"},
        {"name": "test28", "url": "https://devyatkin.dev/28"},
        {"name": "test29", "url": "https://devyatkin.dev/29"},
        {"name": "test30", "url": "https://devyatkin.dev/30"},
        {"name": "test31", "url": "https://devyatkin.dev/31"},
        {"name": "test32", "url": "https://devyatkin.dev/32"},
        {"name": "test33", "url": "https://devyatkin.dev/33"},
        {"name": "test34", "url": "https://devyatkin.dev/34"},
        {"name": "test35", "url": "https://devyatkin.dev/35"},
        {"name": "test36", "url": "https://devyatkin.dev/36"},
        {"name": "test37", "url": "https://devyatkin.dev/37"},
        {"name": "test38", "url": "https://devyatkin.dev/38"},
        {"name": "test39", "url": "https://devyatkin.dev/39"},
        {"name": "test40", "url": "https://devyatkin.dev/40"},
        {"name": "test41", "url": "https://devyatkin.dev/41"},
        {"name": "test42", "url": "https://devyatkin.dev/42"},
        {"name": "test43", "url": "https://devyatkin.dev/43"},
        {"name": "test44", "url": "https://devyatkin.dev/44"},
        {"name": "test45", "url": "https://devyatkin.dev/45"},
        {"name": "test46", "url": "https://devyatkin.dev/46"},
        {"name": "test47", "url": "https://devyatkin.dev/47"},
        {"name": "test48", "url": "https://devyatkin.dev/48"},
        {"name": "test49", "url": "https://devyatkin.dev/49"},
        {"name": "test50", "url": "https://devyatkin.dev/50"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestProductPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"name": "test1", "url": "https://devyatkin.dev/1"},
        {"name": "test2", "url": "https://devyatkin.dev/2"},
        {"name": "test3", "url": "https://devyatkin.dev/3"},
        {"name": "test4", "url": "https://devyatkin.dev/4"},
        {"name": "test5", "url": "https://devyatkin.dev/5"},
        {"name": "test6", "url": "https://devyatkin.dev/6"},
        {"name": "test7", "url": "https://devyatkin.dev/7"},
        {"name": "test8", "url": "https://devyatkin.dev/8"},
        {"name": "test9", "url": "https://devyatkin.dev/9"},
        {"name": "test10", "url": "https://devyatkin.dev/10"},
        {"name": "test11", "url": "https://devyatkin.dev/11"},
        {"name": "test12", "url": "https://devyatkin.dev/12"},
        {"name": "test13", "url": "https://devyatkin.dev/13"},
        {"name": "test14", "url": "https://devyatkin.dev/14"},
        {"name": "test15", "url": "https://devyatkin.dev/15"},
        {"name": "test16", "url": "https://devyatkin.dev/16"},
        {"name": "test17", "url": "https://devyatkin.dev/17"},
        {"name": "test18", "url": "https://devyatkin.dev/18"},
        {"name": "test19", "url": "https://devyatkin.dev/19"},
        {"name": "test20", "url": "https://devyatkin.dev/20"},
        {"name": "test21", "url": "https://devyatkin.dev/21"},
        {"name": "test22", "url": "https://devyatkin.dev/22"},
        {"name": "test23", "url": "https://devyatkin.dev/23"},
        {"name": "test24", "url": "https://devyatkin.dev/24"},
        {"name": "test25", "url": "https://devyatkin.dev/25"},
        {"name": "test26", "url": "https://devyatkin.dev/26"},
        {"name": "test27", "url": "https://devyatkin.dev/27"},
        {"name": "test28", "url": "https://devyatkin.dev/28"},
        {"name": "test29", "url": "https://devyatkin.dev/29"},
        {"name": "test30", "url": "https://devyatkin.dev/30"},
        {"name": "test31", "url": "https://devyatkin.dev/31"},
        {"name": "test32", "url": "https://devyatkin.dev/32"},
        {"name": "test33", "url": "https://devyatkin.dev/33"},
        {"name": "test34", "url": "https://devyatkin.dev/34"},
        {"name": "test35", "url": "https://devyatkin.dev/35"},
        {"name": "test36", "url": "https://devyatkin.dev/36"},
        {"name": "test37", "url": "https://devyatkin.dev/37"},
        {"name": "test38", "url": "https://devyatkin.dev/38"},
        {"name": "test39", "url": "https://devyatkin.dev/39"},
        {"name": "test40", "url": "https://devyatkin.dev/40"},
        {"name": "test41", "url": "https://devyatkin.dev/41"},
        {"name": "test42", "url": "https://devyatkin.dev/42"},
        {"name": "test43", "url": "https://devyatkin.dev/43"},
        {"name": "test44", "url": "https://devyatkin.dev/44"},
        {"name": "test45", "url": "https://devyatkin.dev/45"},
        {"name": "test46", "url": "https://devyatkin.dev/46"},
        {"name": "test47", "url": "https://devyatkin.dev/47"},
        {"name": "test48", "url": "https://devyatkin.dev/48"},
        {"name": "test49", "url": "https://devyatkin.dev/49"},
        {"name": "test50", "url": "https://devyatkin.dev/50"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"name": "test101", "url": "https://devyatkin.dev/101"},
        {"name": "test102", "url": "https://devyatkin.dev/102"},
        {"name": "test103", "url": "https://devyatkin.dev/103"},
        {"name": "test104", "url": "https://devyatkin.dev/104"},
        {"name": "test105", "url": "https://devyatkin.dev/105"},
        {"name": "test106", "url": "https://devyatkin.dev/106"},
        {"name": "test107", "url": "https://devyatkin.dev/107"},
        {"name": "test108", "url": "https://devyatkin.dev/108"},
        {"name": "test109", "url": "https://devyatkin.dev/109"},
        {"name": "test110", "url": "https://devyatkin.dev/110"},
        {"name": "test111", "url": "https://devyatkin.dev/111"},
        {"name": "test112", "url": "https://devyatkin.dev/112"},
        {"name": "test113", "url": "https://devyatkin.dev/113"},
        {"name": "test114", "url": "https://devyatkin.dev/114"},
        {"name": "test115", "url": "https://devyatkin.dev/115"},
        {"name": "test116", "url": "https://devyatkin.dev/116"},
        {"name": "test117", "url": "https://devyatkin.dev/117"},
        {"name": "test118", "url": "https://devyatkin.dev/118"},
        {"name": "test119", "url": "https://devyatkin.dev/119"},
        {"name": "test120", "url": "https://devyatkin.dev/120"},
        {"name": "test121", "url": "https://devyatkin.dev/121"},
        {"name": "test122", "url": "https://devyatkin.dev/122"},
        {"name": "test123", "url": "https://devyatkin.dev/123"},
        {"name": "test124", "url": "https://devyatkin.dev/124"},
        {"name": "test125", "url": "https://devyatkin.dev/125"},
        {"name": "test126", "url": "https://devyatkin.dev/126"},
        {"name": "test127", "url": "https://devyatkin.dev/127"},
        {"name": "test128", "url": "https://devyatkin.dev/128"},
        {"name": "test129", "url": "https://devyatkin.dev/129"},
        {"name": "test130", "url": "https://devyatkin.dev/130"},
        {"name": "test131", "url": "https://devyatkin.dev/131"},
        {"name": "test132", "url": "https://devyatkin.dev/132"},
        {"name": "test133", "url": "https://devyatkin.dev/133"},
        {"name": "test134", "url": "https://devyatkin.dev/134"},
        {"name": "test135", "url": "https://devyatkin.dev/135"},
        {"name": "test136", "url": "https://devyatkin.dev/136"},
        {"name": "test137", "url": "https://devyatkin.dev/137"},
        {"name": "test138", "url": "https://devyatkin.dev/138"},
        {"name": "test139", "url": "https://devyatkin.dev/139"},
        {"name": "test140", "url": "https://devyatkin.dev/140"},
        {"name": "test141", "url": "https://devyatkin.dev/141"},
        {"name": "test142", "url": "https://devyatkin.dev/142"},
        {"name": "test143", "url": "https://devyatkin.dev/143"},
        {"name": "test144", "url": "https://devyatkin.dev/144"},
        {"name": "test145", "url": "https://devyatkin.dev/145"},
        {"name": "test146", "url": "https://devyatkin.dev/146"},
        {"name": "test147", "url": "https://devyatkin.dev/147"},
        {"name": "test148", "url": "https://devyatkin.dev/148"},
        {"name": "test149", "url": "https://devyatkin.dev/149"},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test141", "url": "https://devyatkin.dev/141"},
        {"name": "test142", "url": "https://devyatkin.dev/142"},
        {"name": "test143", "url": "https://devyatkin.dev/143"},
        {"name": "test144", "url": "https://devyatkin.dev/144"},
        {"name": "test145", "url": "https://devyatkin.dev/145"},
        {"name": "test146", "url": "https://devyatkin.dev/146"},
        {"name": "test147", "url": "https://devyatkin.dev/147"},
        {"name": "test148", "url": "https://devyatkin.dev/148"},
        {"name": "test149", "url": "https://devyatkin.dev/149"},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestProductPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"name": "test51", "url": "https://devyatkin.dev/51"},
        {"name": "test52", "url": "https://devyatkin.dev/52"},
        {"name": "test53", "url": "https://devyatkin.dev/53"},
        {"name": "test54", "url": "https://devyatkin.dev/54"},
        {"name": "test55", "url": "https://devyatkin.dev/55"},
        {"name": "test56", "url": "https://devyatkin.dev/56"},
        {"name": "test57", "url": "https://devyatkin.dev/57"},
        {"name": "test58", "url": "https://devyatkin.dev/58"},
        {"name": "test59", "url": "https://devyatkin.dev/59"},
        {"name": "test60", "url": "https://devyatkin.dev/60"},
        {"name": "test61", "url": "https://devyatkin.dev/61"},
        {"name": "test62", "url": "https://devyatkin.dev/62"},
        {"name": "test63", "url": "https://devyatkin.dev/63"},
        {"name": "test64", "url": "https://devyatkin.dev/64"},
        {"name": "test65", "url": "https://devyatkin.dev/65"},
        {"name": "test66", "url": "https://devyatkin.dev/66"},
        {"name": "test67", "url": "https://devyatkin.dev/67"},
        {"name": "test68", "url": "https://devyatkin.dev/68"},
        {"name": "test69", "url": "https://devyatkin.dev/69"},
        {"name": "test70", "url": "https://devyatkin.dev/70"},
        {"name": "test71", "url": "https://devyatkin.dev/71"},
        {"name": "test72", "url": "https://devyatkin.dev/72"},
        {"name": "test73", "url": "https://devyatkin.dev/73"},
        {"name": "test74", "url": "https://devyatkin.dev/74"},
        {"name": "test75", "url": "https://devyatkin.dev/75"},
        {"name": "test76", "url": "https://devyatkin.dev/76"},
        {"name": "test77", "url": "https://devyatkin.dev/77"},
        {"name": "test78", "url": "https://devyatkin.dev/78"},
        {"name": "test79", "url": "https://devyatkin.dev/79"},
        {"name": "test80", "url": "https://devyatkin.dev/80"},
        {"name": "test81", "url": "https://devyatkin.dev/81"},
        {"name": "test82", "url": "https://devyatkin.dev/82"},
        {"name": "test83", "url": "https://devyatkin.dev/83"},
        {"name": "test84", "url": "https://devyatkin.dev/84"},
        {"name": "test85", "url": "https://devyatkin.dev/85"},
        {"name": "test86", "url": "https://devyatkin.dev/86"},
        {"name": "test87", "url": "https://devyatkin.dev/87"},
        {"name": "test88", "url": "https://devyatkin.dev/88"},
        {"name": "test89", "url": "https://devyatkin.dev/89"},
        {"name": "test90", "url": "https://devyatkin.dev/90"},
        {"name": "test91", "url": "https://devyatkin.dev/91"},
        {"name": "test92", "url": "https://devyatkin.dev/92"},
        {"name": "test93", "url": "https://devyatkin.dev/93"},
        {"name": "test94", "url": "https://devyatkin.dev/94"},
        {"name": "test95", "url": "https://devyatkin.dev/95"},
        {"name": "test96", "url": "https://devyatkin.dev/96"},
        {"name": "test97", "url": "https://devyatkin.dev/97"},
        {"name": "test98", "url": "https://devyatkin.dev/98"},
        {"name": "test99", "url": "https://devyatkin.dev/99"},
        {"name": "test100", "url": "https://devyatkin.dev/100"},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test1", "url": "https://devyatkin.dev/1"},
        {"name": "test2", "url": "https://devyatkin.dev/2"},
        {"name": "test3", "url": "https://devyatkin.dev/3"},
        {"name": "test4", "url": "https://devyatkin.dev/4"},
        {"name": "test5", "url": "https://devyatkin.dev/5"},
        {"name": "test6", "url": "https://devyatkin.dev/6"},
        {"name": "test7", "url": "https://devyatkin.dev/7"},
        {"name": "test8", "url": "https://devyatkin.dev/8"},
        {"name": "test9", "url": "https://devyatkin.dev/9"},
        {"name": "test10", "url": "https://devyatkin.dev/10"},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}

snapshots["TestWPPaginator.test_default_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestWPPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestWPPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestWPPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
        {"reserved": False, "substitutable": True},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_default_paginator 1"] = {
    "items": [
        {"name": "test1"},
        {"name": "test2"},
        {"name": "test3"},
        {"name": "test4"},
        {"name": "test5"},
        {"name": "test6"},
        {"name": "test7"},
        {"name": "test8"},
        {"name": "test9"},
        {"name": "test10"},
        {"name": "test11"},
        {"name": "test12"},
        {"name": "test13"},
        {"name": "test14"},
        {"name": "test15"},
        {"name": "test16"},
        {"name": "test17"},
        {"name": "test18"},
        {"name": "test19"},
        {"name": "test20"},
        {"name": "test21"},
        {"name": "test22"},
        {"name": "test23"},
        {"name": "test24"},
        {"name": "test25"},
        {"name": "test26"},
        {"name": "test27"},
        {"name": "test28"},
        {"name": "test29"},
        {"name": "test30"},
        {"name": "test31"},
        {"name": "test32"},
        {"name": "test33"},
        {"name": "test34"},
        {"name": "test35"},
        {"name": "test36"},
        {"name": "test37"},
        {"name": "test38"},
        {"name": "test39"},
        {"name": "test40"},
        {"name": "test41"},
        {"name": "test42"},
        {"name": "test43"},
        {"name": "test44"},
        {"name": "test45"},
        {"name": "test46"},
        {"name": "test47"},
        {"name": "test48"},
        {"name": "test49"},
        {"name": "test50"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"name": "test1"},
        {"name": "test2"},
        {"name": "test3"},
        {"name": "test4"},
        {"name": "test5"},
        {"name": "test6"},
        {"name": "test7"},
        {"name": "test8"},
        {"name": "test9"},
        {"name": "test10"},
        {"name": "test11"},
        {"name": "test12"},
        {"name": "test13"},
        {"name": "test14"},
        {"name": "test15"},
        {"name": "test16"},
        {"name": "test17"},
        {"name": "test18"},
        {"name": "test19"},
        {"name": "test20"},
        {"name": "test21"},
        {"name": "test22"},
        {"name": "test23"},
        {"name": "test24"},
        {"name": "test25"},
        {"name": "test26"},
        {"name": "test27"},
        {"name": "test28"},
        {"name": "test29"},
        {"name": "test30"},
        {"name": "test31"},
        {"name": "test32"},
        {"name": "test33"},
        {"name": "test34"},
        {"name": "test35"},
        {"name": "test36"},
        {"name": "test37"},
        {"name": "test38"},
        {"name": "test39"},
        {"name": "test40"},
        {"name": "test41"},
        {"name": "test42"},
        {"name": "test43"},
        {"name": "test44"},
        {"name": "test45"},
        {"name": "test46"},
        {"name": "test47"},
        {"name": "test48"},
        {"name": "test49"},
        {"name": "test50"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"name": "test101"},
        {"name": "test102"},
        {"name": "test103"},
        {"name": "test104"},
        {"name": "test105"},
        {"name": "test106"},
        {"name": "test107"},
        {"name": "test108"},
        {"name": "test109"},
        {"name": "test110"},
        {"name": "test111"},
        {"name": "test112"},
        {"name": "test113"},
        {"name": "test114"},
        {"name": "test115"},
        {"name": "test116"},
        {"name": "test117"},
        {"name": "test118"},
        {"name": "test119"},
        {"name": "test120"},
        {"name": "test121"},
        {"name": "test122"},
        {"name": "test123"},
        {"name": "test124"},
        {"name": "test125"},
        {"name": "test126"},
        {"name": "test127"},
        {"name": "test128"},
        {"name": "test129"},
        {"name": "test130"},
        {"name": "test131"},
        {"name": "test132"},
        {"name": "test133"},
        {"name": "test134"},
        {"name": "test135"},
        {"name": "test136"},
        {"name": "test137"},
        {"name": "test138"},
        {"name": "test139"},
        {"name": "test140"},
        {"name": "test141"},
        {"name": "test142"},
        {"name": "test143"},
        {"name": "test144"},
        {"name": "test145"},
        {"name": "test146"},
        {"name": "test147"},
        {"name": "test148"},
        {"name": "test149"},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test141"},
        {"name": "test142"},
        {"name": "test143"},
        {"name": "test144"},
        {"name": "test145"},
        {"name": "test146"},
        {"name": "test147"},
        {"name": "test148"},
        {"name": "test149"},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"name": "test51"},
        {"name": "test52"},
        {"name": "test53"},
        {"name": "test54"},
        {"name": "test55"},
        {"name": "test56"},
        {"name": "test57"},
        {"name": "test58"},
        {"name": "test59"},
        {"name": "test60"},
        {"name": "test61"},
        {"name": "test62"},
        {"name": "test63"},
        {"name": "test64"},
        {"name": "test65"},
        {"name": "test66"},
        {"name": "test67"},
        {"name": "test68"},
        {"name": "test69"},
        {"name": "test70"},
        {"name": "test71"},
        {"name": "test72"},
        {"name": "test73"},
        {"name": "test74"},
        {"name": "test75"},
        {"name": "test76"},
        {"name": "test77"},
        {"name": "test78"},
        {"name": "test79"},
        {"name": "test80"},
        {"name": "test81"},
        {"name": "test82"},
        {"name": "test83"},
        {"name": "test84"},
        {"name": "test85"},
        {"name": "test86"},
        {"name": "test87"},
        {"name": "test88"},
        {"name": "test89"},
        {"name": "test90"},
        {"name": "test91"},
        {"name": "test92"},
        {"name": "test93"},
        {"name": "test94"},
        {"name": "test95"},
        {"name": "test96"},
        {"name": "test97"},
        {"name": "test98"},
        {"name": "test99"},
        {"name": "test100"},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test1"},
        {"name": "test2"},
        {"name": "test3"},
        {"name": "test4"},
        {"name": "test5"},
        {"name": "test6"},
        {"name": "test7"},
        {"name": "test8"},
        {"name": "test9"},
        {"name": "test10"},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}
