# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
"""Autogenerated snapshots by snapshottest."""

from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots["TestProduct.test_product_create 1"] = {
    "name": "Product1",
    "price": 123.99,
    "url": "product1",
}
