# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots["TestEmptyWishlist.test_empty_wishlist_full_update 1"] = {
    "name": "test-updated",
    "username": "test-user",
}

snapshots["TestEmptyWishlist.test_empty_wishlist_full_update_admin 1"] = {
    "name": "test-updated",
    "username": "test-user",
}

snapshots["TestEmptyWishlist.test_empty_wishlists 1"] = [
    {"name": "test4", "username": "test-user"},
    {"name": "test3", "username": "test-user"},
    {"name": "test2", "username": "test-user"},
    {"name": "test1", "username": "test-user"},
]

snapshots["TestEmptyWishlist.test_empty_wishlists_paginator_limit 1"] = [
    {"name": "test4", "username": "test-user"},
    {"name": "test3", "username": "test-user"},
]

snapshots["TestProduct.test_product_create 1"] = {
    "name": "Product1",
    "url": "https://devyatkin.dev",
    "username": "test-user",
}

snapshots["TestProduct.test_product_full_update 1"] = {
    "name": "test-updated",
    "url": "https://ya.ru",
    "username": "test-user",
}

snapshots["TestProduct.test_product_full_update_admin 1"] = {
    "name": "test-updated",
    "url": "https://ya.ru",
    "username": "test-user",
}

snapshots["TestProduct.test_product_paginator_limit 1"] = {
    "items": [
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "test-user"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "test-user"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "test-user"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "test-user"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "test-user"},
    ],
    "links": {
        "first": "/api/v1/product?size=5&page=1",
        "last": "/api/v1/product?size=5&page=2",
        "next": "/api/v1/product?size=5&page=2",
        "prev": None,
        "self": "/api/v1/product?size=5",
    },
    "page": 1,
    "size": 5,
    "total": 9,
}

snapshots["TestProduct.test_product_partial_update 1"] = {
    "name": "partial-updated-name",
    "url": "https://devyatkin.dev/1",
    "username": "test-user",
}

snapshots["TestProduct.test_product_partial_update_admin 1"] = {
    "name": "partial-updated-name",
    "url": "https://devyatkin.dev/1",
    "username": "test-user",
}

snapshots["TestProduct.test_product_read 1"] = {
    "name": "test",
    "url": "https://devyatkin.dev/1",
    "username": "test-user",
}

snapshots["TestProduct.test_products 1"] = {
    "items": [
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "test-user"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "test-user"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "test-user"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "test-user"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "test-user"},
        {"name": "test4", "url": "https://devyatkin.dev/4", "username": "test-user"},
        {"name": "test3", "url": "https://devyatkin.dev/3", "username": "test-user"},
        {"name": "test2", "url": "https://devyatkin.dev/2", "username": "test-user"},
        {"name": "test1", "url": "https://devyatkin.dev/1", "username": "test-user"},
    ],
    "links": {
        "first": "/api/v1/product?page=1",
        "last": "/api/v1/product?page=1",
        "next": None,
        "prev": None,
        "self": "/api/v1/product",
    },
    "page": 1,
    "size": 50,
    "total": 9,
}

snapshots["TestProductPaginator.test_default_paginator 1"] = {
    "items": [
        {"name": "test149", "url": "https://devyatkin.dev/149", "username": "test-user"},
        {"name": "test148", "url": "https://devyatkin.dev/148", "username": "test-user"},
        {"name": "test147", "url": "https://devyatkin.dev/147", "username": "test-user"},
        {"name": "test146", "url": "https://devyatkin.dev/146", "username": "test-user"},
        {"name": "test145", "url": "https://devyatkin.dev/145", "username": "test-user"},
        {"name": "test144", "url": "https://devyatkin.dev/144", "username": "test-user"},
        {"name": "test143", "url": "https://devyatkin.dev/143", "username": "test-user"},
        {"name": "test142", "url": "https://devyatkin.dev/142", "username": "test-user"},
        {"name": "test141", "url": "https://devyatkin.dev/141", "username": "test-user"},
        {"name": "test140", "url": "https://devyatkin.dev/140", "username": "test-user"},
        {"name": "test139", "url": "https://devyatkin.dev/139", "username": "test-user"},
        {"name": "test138", "url": "https://devyatkin.dev/138", "username": "test-user"},
        {"name": "test137", "url": "https://devyatkin.dev/137", "username": "test-user"},
        {"name": "test136", "url": "https://devyatkin.dev/136", "username": "test-user"},
        {"name": "test135", "url": "https://devyatkin.dev/135", "username": "test-user"},
        {"name": "test134", "url": "https://devyatkin.dev/134", "username": "test-user"},
        {"name": "test133", "url": "https://devyatkin.dev/133", "username": "test-user"},
        {"name": "test132", "url": "https://devyatkin.dev/132", "username": "test-user"},
        {"name": "test131", "url": "https://devyatkin.dev/131", "username": "test-user"},
        {"name": "test130", "url": "https://devyatkin.dev/130", "username": "test-user"},
        {"name": "test129", "url": "https://devyatkin.dev/129", "username": "test-user"},
        {"name": "test128", "url": "https://devyatkin.dev/128", "username": "test-user"},
        {"name": "test127", "url": "https://devyatkin.dev/127", "username": "test-user"},
        {"name": "test126", "url": "https://devyatkin.dev/126", "username": "test-user"},
        {"name": "test125", "url": "https://devyatkin.dev/125", "username": "test-user"},
        {"name": "test124", "url": "https://devyatkin.dev/124", "username": "test-user"},
        {"name": "test123", "url": "https://devyatkin.dev/123", "username": "test-user"},
        {"name": "test122", "url": "https://devyatkin.dev/122", "username": "test-user"},
        {"name": "test121", "url": "https://devyatkin.dev/121", "username": "test-user"},
        {"name": "test120", "url": "https://devyatkin.dev/120", "username": "test-user"},
        {"name": "test119", "url": "https://devyatkin.dev/119", "username": "test-user"},
        {"name": "test118", "url": "https://devyatkin.dev/118", "username": "test-user"},
        {"name": "test117", "url": "https://devyatkin.dev/117", "username": "test-user"},
        {"name": "test116", "url": "https://devyatkin.dev/116", "username": "test-user"},
        {"name": "test115", "url": "https://devyatkin.dev/115", "username": "test-user"},
        {"name": "test114", "url": "https://devyatkin.dev/114", "username": "test-user"},
        {"name": "test113", "url": "https://devyatkin.dev/113", "username": "test-user"},
        {"name": "test112", "url": "https://devyatkin.dev/112", "username": "test-user"},
        {"name": "test111", "url": "https://devyatkin.dev/111", "username": "test-user"},
        {"name": "test110", "url": "https://devyatkin.dev/110", "username": "test-user"},
        {"name": "test109", "url": "https://devyatkin.dev/109", "username": "test-user"},
        {"name": "test108", "url": "https://devyatkin.dev/108", "username": "test-user"},
        {"name": "test107", "url": "https://devyatkin.dev/107", "username": "test-user"},
        {"name": "test106", "url": "https://devyatkin.dev/106", "username": "test-user"},
        {"name": "test105", "url": "https://devyatkin.dev/105", "username": "test-user"},
        {"name": "test104", "url": "https://devyatkin.dev/104", "username": "test-user"},
        {"name": "test103", "url": "https://devyatkin.dev/103", "username": "test-user"},
        {"name": "test102", "url": "https://devyatkin.dev/102", "username": "test-user"},
        {"name": "test101", "url": "https://devyatkin.dev/101", "username": "test-user"},
        {"name": "test100", "url": "https://devyatkin.dev/100", "username": "test-user"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestProductPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"name": "test149", "url": "https://devyatkin.dev/149", "username": "test-user"},
        {"name": "test148", "url": "https://devyatkin.dev/148", "username": "test-user"},
        {"name": "test147", "url": "https://devyatkin.dev/147", "username": "test-user"},
        {"name": "test146", "url": "https://devyatkin.dev/146", "username": "test-user"},
        {"name": "test145", "url": "https://devyatkin.dev/145", "username": "test-user"},
        {"name": "test144", "url": "https://devyatkin.dev/144", "username": "test-user"},
        {"name": "test143", "url": "https://devyatkin.dev/143", "username": "test-user"},
        {"name": "test142", "url": "https://devyatkin.dev/142", "username": "test-user"},
        {"name": "test141", "url": "https://devyatkin.dev/141", "username": "test-user"},
        {"name": "test140", "url": "https://devyatkin.dev/140", "username": "test-user"},
        {"name": "test139", "url": "https://devyatkin.dev/139", "username": "test-user"},
        {"name": "test138", "url": "https://devyatkin.dev/138", "username": "test-user"},
        {"name": "test137", "url": "https://devyatkin.dev/137", "username": "test-user"},
        {"name": "test136", "url": "https://devyatkin.dev/136", "username": "test-user"},
        {"name": "test135", "url": "https://devyatkin.dev/135", "username": "test-user"},
        {"name": "test134", "url": "https://devyatkin.dev/134", "username": "test-user"},
        {"name": "test133", "url": "https://devyatkin.dev/133", "username": "test-user"},
        {"name": "test132", "url": "https://devyatkin.dev/132", "username": "test-user"},
        {"name": "test131", "url": "https://devyatkin.dev/131", "username": "test-user"},
        {"name": "test130", "url": "https://devyatkin.dev/130", "username": "test-user"},
        {"name": "test129", "url": "https://devyatkin.dev/129", "username": "test-user"},
        {"name": "test128", "url": "https://devyatkin.dev/128", "username": "test-user"},
        {"name": "test127", "url": "https://devyatkin.dev/127", "username": "test-user"},
        {"name": "test126", "url": "https://devyatkin.dev/126", "username": "test-user"},
        {"name": "test125", "url": "https://devyatkin.dev/125", "username": "test-user"},
        {"name": "test124", "url": "https://devyatkin.dev/124", "username": "test-user"},
        {"name": "test123", "url": "https://devyatkin.dev/123", "username": "test-user"},
        {"name": "test122", "url": "https://devyatkin.dev/122", "username": "test-user"},
        {"name": "test121", "url": "https://devyatkin.dev/121", "username": "test-user"},
        {"name": "test120", "url": "https://devyatkin.dev/120", "username": "test-user"},
        {"name": "test119", "url": "https://devyatkin.dev/119", "username": "test-user"},
        {"name": "test118", "url": "https://devyatkin.dev/118", "username": "test-user"},
        {"name": "test117", "url": "https://devyatkin.dev/117", "username": "test-user"},
        {"name": "test116", "url": "https://devyatkin.dev/116", "username": "test-user"},
        {"name": "test115", "url": "https://devyatkin.dev/115", "username": "test-user"},
        {"name": "test114", "url": "https://devyatkin.dev/114", "username": "test-user"},
        {"name": "test113", "url": "https://devyatkin.dev/113", "username": "test-user"},
        {"name": "test112", "url": "https://devyatkin.dev/112", "username": "test-user"},
        {"name": "test111", "url": "https://devyatkin.dev/111", "username": "test-user"},
        {"name": "test110", "url": "https://devyatkin.dev/110", "username": "test-user"},
        {"name": "test109", "url": "https://devyatkin.dev/109", "username": "test-user"},
        {"name": "test108", "url": "https://devyatkin.dev/108", "username": "test-user"},
        {"name": "test107", "url": "https://devyatkin.dev/107", "username": "test-user"},
        {"name": "test106", "url": "https://devyatkin.dev/106", "username": "test-user"},
        {"name": "test105", "url": "https://devyatkin.dev/105", "username": "test-user"},
        {"name": "test104", "url": "https://devyatkin.dev/104", "username": "test-user"},
        {"name": "test103", "url": "https://devyatkin.dev/103", "username": "test-user"},
        {"name": "test102", "url": "https://devyatkin.dev/102", "username": "test-user"},
        {"name": "test101", "url": "https://devyatkin.dev/101", "username": "test-user"},
        {"name": "test100", "url": "https://devyatkin.dev/100", "username": "test-user"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"name": "test49", "url": "https://devyatkin.dev/49", "username": "test-user"},
        {"name": "test48", "url": "https://devyatkin.dev/48", "username": "test-user"},
        {"name": "test47", "url": "https://devyatkin.dev/47", "username": "test-user"},
        {"name": "test46", "url": "https://devyatkin.dev/46", "username": "test-user"},
        {"name": "test45", "url": "https://devyatkin.dev/45", "username": "test-user"},
        {"name": "test44", "url": "https://devyatkin.dev/44", "username": "test-user"},
        {"name": "test43", "url": "https://devyatkin.dev/43", "username": "test-user"},
        {"name": "test42", "url": "https://devyatkin.dev/42", "username": "test-user"},
        {"name": "test41", "url": "https://devyatkin.dev/41", "username": "test-user"},
        {"name": "test40", "url": "https://devyatkin.dev/40", "username": "test-user"},
        {"name": "test39", "url": "https://devyatkin.dev/39", "username": "test-user"},
        {"name": "test38", "url": "https://devyatkin.dev/38", "username": "test-user"},
        {"name": "test37", "url": "https://devyatkin.dev/37", "username": "test-user"},
        {"name": "test36", "url": "https://devyatkin.dev/36", "username": "test-user"},
        {"name": "test35", "url": "https://devyatkin.dev/35", "username": "test-user"},
        {"name": "test34", "url": "https://devyatkin.dev/34", "username": "test-user"},
        {"name": "test33", "url": "https://devyatkin.dev/33", "username": "test-user"},
        {"name": "test32", "url": "https://devyatkin.dev/32", "username": "test-user"},
        {"name": "test31", "url": "https://devyatkin.dev/31", "username": "test-user"},
        {"name": "test30", "url": "https://devyatkin.dev/30", "username": "test-user"},
        {"name": "test29", "url": "https://devyatkin.dev/29", "username": "test-user"},
        {"name": "test28", "url": "https://devyatkin.dev/28", "username": "test-user"},
        {"name": "test27", "url": "https://devyatkin.dev/27", "username": "test-user"},
        {"name": "test26", "url": "https://devyatkin.dev/26", "username": "test-user"},
        {"name": "test25", "url": "https://devyatkin.dev/25", "username": "test-user"},
        {"name": "test24", "url": "https://devyatkin.dev/24", "username": "test-user"},
        {"name": "test23", "url": "https://devyatkin.dev/23", "username": "test-user"},
        {"name": "test22", "url": "https://devyatkin.dev/22", "username": "test-user"},
        {"name": "test21", "url": "https://devyatkin.dev/21", "username": "test-user"},
        {"name": "test20", "url": "https://devyatkin.dev/20", "username": "test-user"},
        {"name": "test19", "url": "https://devyatkin.dev/19", "username": "test-user"},
        {"name": "test18", "url": "https://devyatkin.dev/18", "username": "test-user"},
        {"name": "test17", "url": "https://devyatkin.dev/17", "username": "test-user"},
        {"name": "test16", "url": "https://devyatkin.dev/16", "username": "test-user"},
        {"name": "test15", "url": "https://devyatkin.dev/15", "username": "test-user"},
        {"name": "test14", "url": "https://devyatkin.dev/14", "username": "test-user"},
        {"name": "test13", "url": "https://devyatkin.dev/13", "username": "test-user"},
        {"name": "test12", "url": "https://devyatkin.dev/12", "username": "test-user"},
        {"name": "test11", "url": "https://devyatkin.dev/11", "username": "test-user"},
        {"name": "test10", "url": "https://devyatkin.dev/10", "username": "test-user"},
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "test-user"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "test-user"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "test-user"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "test-user"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "test-user"},
        {"name": "test4", "url": "https://devyatkin.dev/4", "username": "test-user"},
        {"name": "test3", "url": "https://devyatkin.dev/3", "username": "test-user"},
        {"name": "test2", "url": "https://devyatkin.dev/2", "username": "test-user"},
        {"name": "test1", "url": "https://devyatkin.dev/1", "username": "test-user"},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test9", "url": "https://devyatkin.dev/9", "username": "test-user"},
        {"name": "test8", "url": "https://devyatkin.dev/8", "username": "test-user"},
        {"name": "test7", "url": "https://devyatkin.dev/7", "username": "test-user"},
        {"name": "test6", "url": "https://devyatkin.dev/6", "username": "test-user"},
        {"name": "test5", "url": "https://devyatkin.dev/5", "username": "test-user"},
        {"name": "test4", "url": "https://devyatkin.dev/4", "username": "test-user"},
        {"name": "test3", "url": "https://devyatkin.dev/3", "username": "test-user"},
        {"name": "test2", "url": "https://devyatkin.dev/2", "username": "test-user"},
        {"name": "test1", "url": "https://devyatkin.dev/1", "username": "test-user"},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestProductPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"name": "test99", "url": "https://devyatkin.dev/99", "username": "test-user"},
        {"name": "test98", "url": "https://devyatkin.dev/98", "username": "test-user"},
        {"name": "test97", "url": "https://devyatkin.dev/97", "username": "test-user"},
        {"name": "test96", "url": "https://devyatkin.dev/96", "username": "test-user"},
        {"name": "test95", "url": "https://devyatkin.dev/95", "username": "test-user"},
        {"name": "test94", "url": "https://devyatkin.dev/94", "username": "test-user"},
        {"name": "test93", "url": "https://devyatkin.dev/93", "username": "test-user"},
        {"name": "test92", "url": "https://devyatkin.dev/92", "username": "test-user"},
        {"name": "test91", "url": "https://devyatkin.dev/91", "username": "test-user"},
        {"name": "test90", "url": "https://devyatkin.dev/90", "username": "test-user"},
        {"name": "test89", "url": "https://devyatkin.dev/89", "username": "test-user"},
        {"name": "test88", "url": "https://devyatkin.dev/88", "username": "test-user"},
        {"name": "test87", "url": "https://devyatkin.dev/87", "username": "test-user"},
        {"name": "test86", "url": "https://devyatkin.dev/86", "username": "test-user"},
        {"name": "test85", "url": "https://devyatkin.dev/85", "username": "test-user"},
        {"name": "test84", "url": "https://devyatkin.dev/84", "username": "test-user"},
        {"name": "test83", "url": "https://devyatkin.dev/83", "username": "test-user"},
        {"name": "test82", "url": "https://devyatkin.dev/82", "username": "test-user"},
        {"name": "test81", "url": "https://devyatkin.dev/81", "username": "test-user"},
        {"name": "test80", "url": "https://devyatkin.dev/80", "username": "test-user"},
        {"name": "test79", "url": "https://devyatkin.dev/79", "username": "test-user"},
        {"name": "test78", "url": "https://devyatkin.dev/78", "username": "test-user"},
        {"name": "test77", "url": "https://devyatkin.dev/77", "username": "test-user"},
        {"name": "test76", "url": "https://devyatkin.dev/76", "username": "test-user"},
        {"name": "test75", "url": "https://devyatkin.dev/75", "username": "test-user"},
        {"name": "test74", "url": "https://devyatkin.dev/74", "username": "test-user"},
        {"name": "test73", "url": "https://devyatkin.dev/73", "username": "test-user"},
        {"name": "test72", "url": "https://devyatkin.dev/72", "username": "test-user"},
        {"name": "test71", "url": "https://devyatkin.dev/71", "username": "test-user"},
        {"name": "test70", "url": "https://devyatkin.dev/70", "username": "test-user"},
        {"name": "test69", "url": "https://devyatkin.dev/69", "username": "test-user"},
        {"name": "test68", "url": "https://devyatkin.dev/68", "username": "test-user"},
        {"name": "test67", "url": "https://devyatkin.dev/67", "username": "test-user"},
        {"name": "test66", "url": "https://devyatkin.dev/66", "username": "test-user"},
        {"name": "test65", "url": "https://devyatkin.dev/65", "username": "test-user"},
        {"name": "test64", "url": "https://devyatkin.dev/64", "username": "test-user"},
        {"name": "test63", "url": "https://devyatkin.dev/63", "username": "test-user"},
        {"name": "test62", "url": "https://devyatkin.dev/62", "username": "test-user"},
        {"name": "test61", "url": "https://devyatkin.dev/61", "username": "test-user"},
        {"name": "test60", "url": "https://devyatkin.dev/60", "username": "test-user"},
        {"name": "test59", "url": "https://devyatkin.dev/59", "username": "test-user"},
        {"name": "test58", "url": "https://devyatkin.dev/58", "username": "test-user"},
        {"name": "test57", "url": "https://devyatkin.dev/57", "username": "test-user"},
        {"name": "test56", "url": "https://devyatkin.dev/56", "username": "test-user"},
        {"name": "test55", "url": "https://devyatkin.dev/55", "username": "test-user"},
        {"name": "test54", "url": "https://devyatkin.dev/54", "username": "test-user"},
        {"name": "test53", "url": "https://devyatkin.dev/53", "username": "test-user"},
        {"name": "test52", "url": "https://devyatkin.dev/52", "username": "test-user"},
        {"name": "test51", "url": "https://devyatkin.dev/51", "username": "test-user"},
        {"name": "test50", "url": "https://devyatkin.dev/50", "username": "test-user"},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestProductPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test149", "url": "https://devyatkin.dev/149", "username": "test-user"},
        {"name": "test148", "url": "https://devyatkin.dev/148", "username": "test-user"},
        {"name": "test147", "url": "https://devyatkin.dev/147", "username": "test-user"},
        {"name": "test146", "url": "https://devyatkin.dev/146", "username": "test-user"},
        {"name": "test145", "url": "https://devyatkin.dev/145", "username": "test-user"},
        {"name": "test144", "url": "https://devyatkin.dev/144", "username": "test-user"},
        {"name": "test143", "url": "https://devyatkin.dev/143", "username": "test-user"},
        {"name": "test142", "url": "https://devyatkin.dev/142", "username": "test-user"},
        {"name": "test141", "url": "https://devyatkin.dev/141", "username": "test-user"},
        {"name": "test140", "url": "https://devyatkin.dev/140", "username": "test-user"},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_default_paginator 1"] = {
    "items": [
        {"name": "test149", "username": "test-user"},
        {"name": "test148", "username": "test-user"},
        {"name": "test147", "username": "test-user"},
        {"name": "test146", "username": "test-user"},
        {"name": "test145", "username": "test-user"},
        {"name": "test144", "username": "test-user"},
        {"name": "test143", "username": "test-user"},
        {"name": "test142", "username": "test-user"},
        {"name": "test141", "username": "test-user"},
        {"name": "test140", "username": "test-user"},
        {"name": "test139", "username": "test-user"},
        {"name": "test138", "username": "test-user"},
        {"name": "test137", "username": "test-user"},
        {"name": "test136", "username": "test-user"},
        {"name": "test135", "username": "test-user"},
        {"name": "test134", "username": "test-user"},
        {"name": "test133", "username": "test-user"},
        {"name": "test132", "username": "test-user"},
        {"name": "test131", "username": "test-user"},
        {"name": "test130", "username": "test-user"},
        {"name": "test129", "username": "test-user"},
        {"name": "test128", "username": "test-user"},
        {"name": "test127", "username": "test-user"},
        {"name": "test126", "username": "test-user"},
        {"name": "test125", "username": "test-user"},
        {"name": "test124", "username": "test-user"},
        {"name": "test123", "username": "test-user"},
        {"name": "test122", "username": "test-user"},
        {"name": "test121", "username": "test-user"},
        {"name": "test120", "username": "test-user"},
        {"name": "test119", "username": "test-user"},
        {"name": "test118", "username": "test-user"},
        {"name": "test117", "username": "test-user"},
        {"name": "test116", "username": "test-user"},
        {"name": "test115", "username": "test-user"},
        {"name": "test114", "username": "test-user"},
        {"name": "test113", "username": "test-user"},
        {"name": "test112", "username": "test-user"},
        {"name": "test111", "username": "test-user"},
        {"name": "test110", "username": "test-user"},
        {"name": "test109", "username": "test-user"},
        {"name": "test108", "username": "test-user"},
        {"name": "test107", "username": "test-user"},
        {"name": "test106", "username": "test-user"},
        {"name": "test105", "username": "test-user"},
        {"name": "test104", "username": "test-user"},
        {"name": "test103", "username": "test-user"},
        {"name": "test102", "username": "test-user"},
        {"name": "test101", "username": "test-user"},
        {"name": "test100", "username": "test-user"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_empty_page_reduced_qs_paginator 1"] = {
    "items": [],
    "page": 16,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_first_page_paginator 1"] = {
    "items": [
        {"name": "test149", "username": "test-user"},
        {"name": "test148", "username": "test-user"},
        {"name": "test147", "username": "test-user"},
        {"name": "test146", "username": "test-user"},
        {"name": "test145", "username": "test-user"},
        {"name": "test144", "username": "test-user"},
        {"name": "test143", "username": "test-user"},
        {"name": "test142", "username": "test-user"},
        {"name": "test141", "username": "test-user"},
        {"name": "test140", "username": "test-user"},
        {"name": "test139", "username": "test-user"},
        {"name": "test138", "username": "test-user"},
        {"name": "test137", "username": "test-user"},
        {"name": "test136", "username": "test-user"},
        {"name": "test135", "username": "test-user"},
        {"name": "test134", "username": "test-user"},
        {"name": "test133", "username": "test-user"},
        {"name": "test132", "username": "test-user"},
        {"name": "test131", "username": "test-user"},
        {"name": "test130", "username": "test-user"},
        {"name": "test129", "username": "test-user"},
        {"name": "test128", "username": "test-user"},
        {"name": "test127", "username": "test-user"},
        {"name": "test126", "username": "test-user"},
        {"name": "test125", "username": "test-user"},
        {"name": "test124", "username": "test-user"},
        {"name": "test123", "username": "test-user"},
        {"name": "test122", "username": "test-user"},
        {"name": "test121", "username": "test-user"},
        {"name": "test120", "username": "test-user"},
        {"name": "test119", "username": "test-user"},
        {"name": "test118", "username": "test-user"},
        {"name": "test117", "username": "test-user"},
        {"name": "test116", "username": "test-user"},
        {"name": "test115", "username": "test-user"},
        {"name": "test114", "username": "test-user"},
        {"name": "test113", "username": "test-user"},
        {"name": "test112", "username": "test-user"},
        {"name": "test111", "username": "test-user"},
        {"name": "test110", "username": "test-user"},
        {"name": "test109", "username": "test-user"},
        {"name": "test108", "username": "test-user"},
        {"name": "test107", "username": "test-user"},
        {"name": "test106", "username": "test-user"},
        {"name": "test105", "username": "test-user"},
        {"name": "test104", "username": "test-user"},
        {"name": "test103", "username": "test-user"},
        {"name": "test102", "username": "test-user"},
        {"name": "test101", "username": "test-user"},
        {"name": "test100", "username": "test-user"},
    ],
    "page": 1,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_last_page_paginator 1"] = {
    "items": [
        {"name": "test49", "username": "test-user"},
        {"name": "test48", "username": "test-user"},
        {"name": "test47", "username": "test-user"},
        {"name": "test46", "username": "test-user"},
        {"name": "test45", "username": "test-user"},
        {"name": "test44", "username": "test-user"},
        {"name": "test43", "username": "test-user"},
        {"name": "test42", "username": "test-user"},
        {"name": "test41", "username": "test-user"},
        {"name": "test40", "username": "test-user"},
        {"name": "test39", "username": "test-user"},
        {"name": "test38", "username": "test-user"},
        {"name": "test37", "username": "test-user"},
        {"name": "test36", "username": "test-user"},
        {"name": "test35", "username": "test-user"},
        {"name": "test34", "username": "test-user"},
        {"name": "test33", "username": "test-user"},
        {"name": "test32", "username": "test-user"},
        {"name": "test31", "username": "test-user"},
        {"name": "test30", "username": "test-user"},
        {"name": "test29", "username": "test-user"},
        {"name": "test28", "username": "test-user"},
        {"name": "test27", "username": "test-user"},
        {"name": "test26", "username": "test-user"},
        {"name": "test25", "username": "test-user"},
        {"name": "test24", "username": "test-user"},
        {"name": "test23", "username": "test-user"},
        {"name": "test22", "username": "test-user"},
        {"name": "test21", "username": "test-user"},
        {"name": "test20", "username": "test-user"},
        {"name": "test19", "username": "test-user"},
        {"name": "test18", "username": "test-user"},
        {"name": "test17", "username": "test-user"},
        {"name": "test16", "username": "test-user"},
        {"name": "test15", "username": "test-user"},
        {"name": "test14", "username": "test-user"},
        {"name": "test13", "username": "test-user"},
        {"name": "test12", "username": "test-user"},
        {"name": "test11", "username": "test-user"},
        {"name": "test10", "username": "test-user"},
        {"name": "test9", "username": "test-user"},
        {"name": "test8", "username": "test-user"},
        {"name": "test7", "username": "test-user"},
        {"name": "test6", "username": "test-user"},
        {"name": "test5", "username": "test-user"},
        {"name": "test4", "username": "test-user"},
        {"name": "test3", "username": "test-user"},
        {"name": "test2", "username": "test-user"},
        {"name": "test1", "username": "test-user"},
    ],
    "page": 3,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_last_page_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test9", "username": "test-user"},
        {"name": "test8", "username": "test-user"},
        {"name": "test7", "username": "test-user"},
        {"name": "test6", "username": "test-user"},
        {"name": "test5", "username": "test-user"},
        {"name": "test4", "username": "test-user"},
        {"name": "test3", "username": "test-user"},
        {"name": "test2", "username": "test-user"},
        {"name": "test1", "username": "test-user"},
    ],
    "page": 15,
    "size": 10,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_next_page_paginator 1"] = {
    "items": [
        {"name": "test99", "username": "test-user"},
        {"name": "test98", "username": "test-user"},
        {"name": "test97", "username": "test-user"},
        {"name": "test96", "username": "test-user"},
        {"name": "test95", "username": "test-user"},
        {"name": "test94", "username": "test-user"},
        {"name": "test93", "username": "test-user"},
        {"name": "test92", "username": "test-user"},
        {"name": "test91", "username": "test-user"},
        {"name": "test90", "username": "test-user"},
        {"name": "test89", "username": "test-user"},
        {"name": "test88", "username": "test-user"},
        {"name": "test87", "username": "test-user"},
        {"name": "test86", "username": "test-user"},
        {"name": "test85", "username": "test-user"},
        {"name": "test84", "username": "test-user"},
        {"name": "test83", "username": "test-user"},
        {"name": "test82", "username": "test-user"},
        {"name": "test81", "username": "test-user"},
        {"name": "test80", "username": "test-user"},
        {"name": "test79", "username": "test-user"},
        {"name": "test78", "username": "test-user"},
        {"name": "test77", "username": "test-user"},
        {"name": "test76", "username": "test-user"},
        {"name": "test75", "username": "test-user"},
        {"name": "test74", "username": "test-user"},
        {"name": "test73", "username": "test-user"},
        {"name": "test72", "username": "test-user"},
        {"name": "test71", "username": "test-user"},
        {"name": "test70", "username": "test-user"},
        {"name": "test69", "username": "test-user"},
        {"name": "test68", "username": "test-user"},
        {"name": "test67", "username": "test-user"},
        {"name": "test66", "username": "test-user"},
        {"name": "test65", "username": "test-user"},
        {"name": "test64", "username": "test-user"},
        {"name": "test63", "username": "test-user"},
        {"name": "test62", "username": "test-user"},
        {"name": "test61", "username": "test-user"},
        {"name": "test60", "username": "test-user"},
        {"name": "test59", "username": "test-user"},
        {"name": "test58", "username": "test-user"},
        {"name": "test57", "username": "test-user"},
        {"name": "test56", "username": "test-user"},
        {"name": "test55", "username": "test-user"},
        {"name": "test54", "username": "test-user"},
        {"name": "test53", "username": "test-user"},
        {"name": "test52", "username": "test-user"},
        {"name": "test51", "username": "test-user"},
        {"name": "test50", "username": "test-user"},
    ],
    "page": 2,
    "size": 50,
    "total": 149,
}

snapshots["TestWishlistPaginator.test_reduced_qs_paginator 1"] = {
    "items": [
        {"name": "test149", "username": "test-user"},
        {"name": "test148", "username": "test-user"},
        {"name": "test147", "username": "test-user"},
        {"name": "test146", "username": "test-user"},
        {"name": "test145", "username": "test-user"},
        {"name": "test144", "username": "test-user"},
        {"name": "test143", "username": "test-user"},
        {"name": "test142", "username": "test-user"},
        {"name": "test141", "username": "test-user"},
        {"name": "test140", "username": "test-user"},
    ],
    "page": 1,
    "size": 10,
    "total": 149,
}
