# Linting: run black, flake8 and small auto fixers.

name: Linter and smoke tests

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ '**' ]

jobs:
  auto-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
#          git config --global user.name 'autoblack'
#          git config --global user.email 'actions@github.com'
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
#          git checkout $GITHUB_HEAD_REF
#          git commit -am "fixup: Format Python code with Black"
#          git push
#          echo "Finished"
#          { exit 0 }

  pre-commit:
    needs: auto-black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - uses: pre-commit/action@v2.0.0
  smoke-test:
    needs: [auto-black, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Test with pytest
        run: |
          cd backend
          python -m pip install pipenv
          pipenv install --deploy --dev
          pipenv run pytest -vm "smoke"
