# Linting: run black, flake8 and small auto fixers.

name: Linter and smoke tests

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ feature/fastapi ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
