# Linting: run black, flake8 and small auto fixers.

name: Linter and smoke tests

on:
  pull_request:
    branches: [ develop, main ]
# TODO: enable
#  push:
#    branches: [ feature/* ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - uses: pre-commit/action@v2.0.0
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Test with pytest
        run: |
          cd backend
          python -m pip install pipenv
          pipenv install --deploy --dev
          pipenv run pytest -vm "smoke"
