# Linting: run black, flake8 and small auto fixers.

name: Linter and smoke tests

on:
  pull_request:
    branches: [ develop, main ]
  push:
#    branches: [ feature/* ]
    branches: [ '**' ]

jobs:
  auto-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format Python code with Black
          file_pattern: backend/*.py
  pre-commit:
    needs: auto-black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - uses: pre-commit/action@v2.0.0
  smoke-test:
    needs: [auto-black, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Test with pytest
        run: |
          cd backend
          python -m pip install pipenv
          pipenv install --deploy --dev
          pipenv run pytest -vm "smoke"
