# Run and upload codecov report.

name: Tests and codecov.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: /opt/yawm/app
      PLATFORM: GITHUB
      API_PORT: 8000
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: |
          cd docker
          docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from app-tests
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
