# Run and upload codecov report.

name: Tests and codecov.

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5430
      DB_USER: test_us1er
      DB_PASSWORD: test_pass
      DB_DATABASE: test_db
      PYTHONPATH: /opt/yawm/app
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: |
          cd docker
          docker-compose -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from app-tests
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
