# Run and upload codecov report.

name: Tests and codecov.

on:
  pull_request:
    branches: [ develop, main ]

jobs:
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
  code-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#- uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
