# Run and upload codecov report.

name: Tests and codecov.

on:
  pull_request:
    branches: [ develop, main ]
#    TODO: remove
  push:
    branches: [ feature/* ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5430
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_DATABASE: test_db
      PYTHONPATH: /opt/yawm/app
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from app-tests
      - uses: codecov/codecov-action@v1
      - name: Uploat codecov report
        with:
          flags: unittests
          fail_ci_if_error: true
