# Run and upload codecov report.

name: Tests and codecov.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: /opt/yawm/app
      PLATFORM: GITHUB
      API_PORT: 8000
      API_DOMAIN: ${{ secrets.API_DOMAIN }}
      API_HOST: ${{ secrets.API_HOST }}
      API_PROTOCOL: ${{ secrets.API_PROTOCOL }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: |
          cd docker
          docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from app-tests
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
