# Run and upload codecov report.

name: "Tests"

on:
  pull_request:
    branches: [ main, release/* ]
  push:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: /home/app
      DB_PORT: 5431
      DB_DATABASE: dev_db
      DB_HOST: localhost
      DB_USER: dev_user
      DB_PASSWORD: dev_pass
      API_PORT: 8000
      API_HOST: 0.0.0.0
      API_DOMAIN: localhost
      API_PROTOCOL: http
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@master
      - name: Run tests via docker
        run: |
          docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from app-tests
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: yawm-backend
          fail_ci_if_error: true
          verbose: true
